from .core import PREDICATES as CORE_PREDICATES
from .biography import PREDICATES as BIOGRAPHY_PREDICATES
from .geography import PREDICATES as GEOGRAPHY_PREDICATES
from .publications import PREDICATES as PUBLICATIONS_PREDICATES
from .science import PREDICATES as SCIENCE_PREDICATES
from .domain_01 import PREDICATES as DOMAIN_01_PREDICATES
from .domain_02 import PREDICATES as DOMAIN_02_PREDICATES
from .domain_03 import PREDICATES as DOMAIN_03_PREDICATES
from .domain_04 import PREDICATES as DOMAIN_04_PREDICATES
from .domain_05 import PREDICATES as DOMAIN_05_PREDICATES
from .domain_06 import PREDICATES as DOMAIN_06_PREDICATES
from .domain_07 import PREDICATES as DOMAIN_07_PREDICATES
from .domain_08 import PREDICATES as DOMAIN_08_PREDICATES
from .domain_09 import PREDICATES as DOMAIN_09_PREDICATES
from .domain_10 import PREDICATES as DOMAIN_10_PREDICATES
from .domain_11 import PREDICATES as DOMAIN_11_PREDICATES
from .domain_12 import PREDICATES as DOMAIN_12_PREDICATES
from .domain_13 import PREDICATES as DOMAIN_13_PREDICATES
from .domain_14 import PREDICATES as DOMAIN_14_PREDICATES
from .domain_15 import PREDICATES as DOMAIN_15_PREDICATES
from .domain_16 import PREDICATES as DOMAIN_16_PREDICATES
from .domain_17 import PREDICATES as DOMAIN_17_PREDICATES
from .domain_18 import PREDICATES as DOMAIN_18_PREDICATES
from .domain_19 import PREDICATES as DOMAIN_19_PREDICATES
from .domain_20 import PREDICATES as DOMAIN_20_PREDICATES
from .domain_21 import PREDICATES as DOMAIN_21_PREDICATES
from .domain_22 import PREDICATES as DOMAIN_22_PREDICATES
from .domain_23 import PREDICATES as DOMAIN_23_PREDICATES
from .domain_24 import PREDICATES as DOMAIN_24_PREDICATES
from .domain_25 import PREDICATES as DOMAIN_25_PREDICATES
from .domain_26 import PREDICATES as DOMAIN_26_PREDICATES
from .domain_27 import PREDICATES as DOMAIN_27_PREDICATES
from .domain_28 import PREDICATES as DOMAIN_28_PREDICATES
from .domain_29 import PREDICATES as DOMAIN_29_PREDICATES
from .domain_30 import PREDICATES as DOMAIN_30_PREDICATES
from .domain_31 import PREDICATES as DOMAIN_31_PREDICATES
from .domain_32 import PREDICATES as DOMAIN_32_PREDICATES
from .domain_33 import PREDICATES as DOMAIN_33_PREDICATES
from .domain_34 import PREDICATES as DOMAIN_34_PREDICATES
from .domain_35 import PREDICATES as DOMAIN_35_PREDICATES
from .domain_36 import PREDICATES as DOMAIN_36_PREDICATES
from .domain_37 import PREDICATES as DOMAIN_37_PREDICATES
from .domain_38 import PREDICATES as DOMAIN_38_PREDICATES
from .domain_39 import PREDICATES as DOMAIN_39_PREDICATES
from .domain_40 import PREDICATES as DOMAIN_40_PREDICATES
from .domain_41 import PREDICATES as DOMAIN_41_PREDICATES
from .domain_42 import PREDICATES as DOMAIN_42_PREDICATES
from .domain_43 import PREDICATES as DOMAIN_43_PREDICATES
from .domain_44 import PREDICATES as DOMAIN_44_PREDICATES
from .domain_45 import PREDICATES as DOMAIN_45_PREDICATES
from .domain_46 import PREDICATES as DOMAIN_46_PREDICATES
from .domain_47 import PREDICATES as DOMAIN_47_PREDICATES
from .domain_48 import PREDICATES as DOMAIN_48_PREDICATES

PREDICATES = {}
for group in (
    CORE_PREDICATES,
    BIOGRAPHY_PREDICATES,
    GEOGRAPHY_PREDICATES,
    PUBLICATIONS_PREDICATES,
    SCIENCE_PREDICATES,
    DOMAIN_01_PREDICATES,
    DOMAIN_02_PREDICATES,
    DOMAIN_03_PREDICATES,
    DOMAIN_04_PREDICATES,
    DOMAIN_05_PREDICATES,
    DOMAIN_06_PREDICATES,
    DOMAIN_07_PREDICATES,
    DOMAIN_08_PREDICATES,
    DOMAIN_09_PREDICATES,
    DOMAIN_10_PREDICATES,
    DOMAIN_11_PREDICATES,
    DOMAIN_12_PREDICATES,
    DOMAIN_13_PREDICATES,
    DOMAIN_14_PREDICATES,
    DOMAIN_15_PREDICATES,
    DOMAIN_16_PREDICATES,
    DOMAIN_17_PREDICATES,
    DOMAIN_18_PREDICATES,
    DOMAIN_19_PREDICATES,
    DOMAIN_20_PREDICATES,
    DOMAIN_21_PREDICATES,
    DOMAIN_22_PREDICATES,
    DOMAIN_23_PREDICATES,
    DOMAIN_24_PREDICATES,
    DOMAIN_25_PREDICATES,
    DOMAIN_26_PREDICATES,
    DOMAIN_27_PREDICATES,
    DOMAIN_28_PREDICATES,
    DOMAIN_29_PREDICATES,
    DOMAIN_30_PREDICATES,
    DOMAIN_31_PREDICATES,
    DOMAIN_32_PREDICATES,
    DOMAIN_33_PREDICATES,
    DOMAIN_34_PREDICATES,
    DOMAIN_35_PREDICATES,
    DOMAIN_36_PREDICATES,
    DOMAIN_37_PREDICATES,
    DOMAIN_38_PREDICATES,
    DOMAIN_39_PREDICATES,
    DOMAIN_40_PREDICATES,
    DOMAIN_41_PREDICATES,
    DOMAIN_42_PREDICATES,
    DOMAIN_43_PREDICATES,
    DOMAIN_44_PREDICATES,
    DOMAIN_45_PREDICATES,
    DOMAIN_46_PREDICATES,
    DOMAIN_47_PREDICATES,
    DOMAIN_48_PREDICATES,
):
    PREDICATES.update(group)
