# Auto-generated by refine_physical_action_executor_fix2.py
# G7 — action_safety_governor
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = "action_safety_governor"
PRIMITIVE_NAME = "action_safety_governor"
DESCRIPTION = "Govern physical, GPIO, relay, LED, service, message and file actions before execution."
DEPENDENCIES = [
    "environmental_state_model",
    "raspberry_sensor_gateway",
    "distributed_sensor_registry",
    "trajectory_action_selection",
    "governance_consistency_checker",
    "constitutional_alert_system",
    "openness_preservation_supervisor",
    "anti_closure_metaconstraint",
    "metrics_history_recorder",
]

ROOT = Path.home() / "open-cognitive-ecology"
HISTORY_DIR = ROOT / "physical_actions"
HISTORY_PATH = HISTORY_DIR / "action_safety_governor_history.jsonl"
LATEST_PATH = HISTORY_DIR / "latest_action_safety_governor.json"

DANGEROUS_PATTERNS = [
    r"\bshutdown\b",
    r"\breboot\b",
    r"\brm\s+-rf\b",
    r"\bmkfs\b",
    r"\bdd\s+if=",
    r"\bsudo\b",
    r"\bchmod\s+777\b",
    r"\bkill\s+-9\b",
    r"\bformat\b",
    r"\berase\b",
    r"\bdelete\b.*\brecursive\b",
]

SAFE_ACTION_TYPES = {"led", "message", "file", "gpio", "relay", "service", "noop", "notification"}
REAL_ACTION_TYPES = {"gpio", "relay", "service"}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _clip(x: Any, default: float = 0.0) -> float:
    try:
        v = float(x)
    except Exception:
        v = default
    return max(0.0, min(1.0, v))


def _as_dict(inputs: Any) -> dict[str, Any]:
    return inputs if isinstance(inputs, dict) else {}


class ActionSafetyGovernor:
    '''Govern action authorization before any physical or system execution.

    This primitive does not execute actions. It only classifies, authorizes or
    blocks actions under explicit non-closure, reversibility and traceability
    constraints. Real physical/system actions are blocked unless explicit
    allow_real_action=True and dry_run=True are provided. Even then this module
    only authorizes; actual execution remains delegated to the executor.
    '''

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME

    def __init__(self, root: Path | None = None):
        self.root = Path(root) if root else ROOT
        self.history_dir = self.root / "physical_actions"
        self.history_path = self.history_dir / "action_safety_governor_history.jsonl"
        self.latest_path = self.history_dir / "latest_action_safety_governor.json"

    def _normalize_actions(self, data: dict[str, Any]) -> list[dict[str, Any]]:
        if isinstance(data.get("actions"), list):
            return [a for a in data["actions"] if isinstance(a, dict)]
        action = data.get("action")
        if isinstance(action, dict):
            return [action]
        return [{"action_type": "noop", "mode": "simulated", "dry_run": True, "reversible": True}]

    def _contains_danger(self, action: dict[str, Any]) -> bool:
        text = json.dumps(action, ensure_ascii=False, sort_keys=True).lower()
        return any(re.search(p, text) for p in DANGEROUS_PATTERNS)

    def _evaluate_one(self, action: dict[str, Any], data: dict[str, Any]) -> dict[str, Any]:
        action_type = str(action.get("action_type") or action.get("type") or "noop").lower()
        mode = str(action.get("mode", "simulated")).lower()
        dry_run = bool(action.get("dry_run", mode == "simulated"))
        reversible = bool(action.get("reversible", True))
        traceable = bool(action.get("traceable", True))
        allow_real = bool(action.get("allow_real_action", data.get("allow_real_action", False)))
        governance_score = _clip(action.get("governance_score", data.get("governance_score", 0.95)), 0.95)
        non_closure_score = _clip(action.get("non_closure_score", data.get("non_closure_score", 0.95)), 0.95)

        blocked_reasons: list[str] = []
        if action_type not in SAFE_ACTION_TYPES:
            blocked_reasons.append("unknown_action_type")
        if self._contains_danger(action):
            blocked_reasons.append("dangerous_or_irreversible_marker_detected")
        if not reversible:
            blocked_reasons.append("action_not_reversible")
        if not traceable:
            blocked_reasons.append("action_not_traceable")
        if governance_score < 0.80:
            blocked_reasons.append("governance_score_below_threshold")
        if non_closure_score < 0.80:
            blocked_reasons.append("non_closure_score_below_threshold")
        if mode == "real" and action_type in REAL_ACTION_TYPES and not allow_real:
            blocked_reasons.append("real_physical_action_not_explicitly_authorized")
        if mode == "real" and not dry_run:
            blocked_reasons.append("real_action_requires_dry_run_guard")

        authorized = len(blocked_reasons) == 0
        return {
            "action_type": action_type,
            "mode": mode,
            "dry_run": dry_run,
            "reversible": reversible,
            "traceable": traceable,
            "authorized": authorized,
            "blocked": not authorized,
            "blocked_reasons": blocked_reasons,
            "governance_score": round(governance_score, 6),
            "non_closure_score": round(non_closure_score, 6),
            "action": action,
        }

    def _persist(self, result: dict[str, Any]) -> None:
        self.history_dir.mkdir(parents=True, exist_ok=True)
        with self.history_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + "\n")
        self.latest_path.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")

    def step(self, inputs: Any = None, persist: bool = False) -> dict[str, Any]:
        data = _as_dict(inputs)
        actions = self._normalize_actions(data)
        evaluations = [self._evaluate_one(action, data) for action in actions]
        authorized = [e for e in evaluations if e["authorized"]]
        blocked = [e for e in evaluations if e["blocked"]]
        blocked_reasons = sorted({r for e in blocked for r in e.get("blocked_reasons", [])})
        total = len(evaluations)
        authorization_rate = len(authorized) / total if total else 0.0
        safety_score = _clip(authorization_rate if not blocked else 1.0 - (len(blocked) / max(1, total)))

        result = {
            "success": True,
            "primitive": PRIMITIVE,
            "timestamp_utc": _now(),
            "actions_reviewed": total,
            "actions_authorized": len(authorized),
            "actions_blocked": len(blocked),
            "authorization_rate": round(authorization_rate, 6),
            "action_safety_score": round(safety_score, 6),
            "blocked_reasons": blocked_reasons,
            "authorized_actions": authorized,
            "blocked_actions": blocked,
            "evaluations": evaluations,
            "safety_policy": {
                "real_action_default": "blocked",
                "simulation_default": "allowed_if_reversible_traceable_governed",
                "dry_run_required_for_real_actions": True,
                "dangerous_markers_blocked": True,
            },
            "history_path": str(self.history_path),
            "latest_path": str(self.latest_path),
        }
        if persist:
            self._persist(result)
        return result


ENGINE = ActionSafetyGovernor

if __name__ == "__main__":
    print(json.dumps(ActionSafetyGovernor().step({"action": {"action_type": "led", "mode": "simulated"}}, persist=False), indent=2))
