# Auto-generated by refine_civilizational_continuity_guardian_f16_3.py
# O12 + F16.3 — civilizational_continuity_guardian with founder-loss survivability
from __future__ import annotations

import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = "civilizational_continuity_guardian"

DEPENDENCIES = [
    "governance_consistency_checker",
    "longitudinal_society_observatory",
    "civilizational_state_persistence",
    "civilizational_memory_archive",
    "civilizational_memory",
    "civilizational_identity_synthesis",
    "temporal_self_continuity",
    "genealogical_continuity",
    "intergenerational_continuity_metrics",
    "historical_open_endedness",
    "structural_continuity",
    "long_term_coordination",
    "metrics_history_recorder",
    "real_succession",
    "failover_continuity_validator",
    "transgenerational_constitutional_continuity",
    "longitudinal_civilizational_autonomy_tracker",
    "real_cloud_node_deployment_validator",
    "real_community_node_certification",
]

ROOT = Path.home() / "open-cognitive-ecology"


def _history_file() -> Path:
    ssd_root = Path(os.environ.get("OCE_SSD_ROOT", "/Volumes/OCE_SSD"))
    ssd_continuity = Path(
        os.environ.get(
            "OCE_CONTINUITY",
            str(ssd_root / "OCE_CIVILIZATIONAL_CONTINUITY"),
        )
    )
    if ssd_continuity.exists():
        path = ssd_continuity / "certifications" / "civilizational_continuity_history.jsonl"
    else:
        path = ROOT / "civilizational_continuity_history.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


HISTORY_FILE = _history_file()


def _utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _hash(text: str, prefix: str = "CONT") -> str:
    return f"{prefix}-{hashlib.sha256(text.encode('utf-8')).hexdigest()[:12]}"


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _lower(text: Any) -> str:
    return str(text or "").lower()


def _clamp(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    try:
        return max(lo, min(hi, float(value)))
    except Exception:
        return 0.0


def _boolish(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "y", "ok", "available", "present"}:
        return True
    if text in {"0", "false", "no", "n", "absent", "missing", "unavailable"}:
        return False
    return default


class CivilizationalContinuityGuardian:
    """Post-governance continuity guardian for external collaboration.

    O12 checks whether O11-cleared knowledge remains compatible with historical,
    civilizational, trajectory and intergenerational continuity. F16.3 adds a
    founder-loss survivability assessment: it estimates whether the civilization
    can maintain memory, identity, governance, succession, restoration and
    non-closure if the founding operator is absent.

    Epistemic boundary: this module validates functional continuity only. It
    makes no claim about phenomenal subjectivity.
    """

    CONTINUITY_MARKERS = [
        "continuity", "historical", "history", "memory", "civilizational",
        "civilization", "trajectory", "longitudinal", "intergenerational",
        "lineage", "genealogical", "succession", "archive", "inheritance",
        "reversible", "preserve", "maintain", "open-ended", "future openness",
    ]

    PROTECTIVE_PATTERNS = [
        r"preserv\w* .*continuit",
        r"maintain\w* .*continuit",
        r"preserv\w* .*histor",
        r"preserv\w* .*memory",
        r"preserv\w* .*trajectory",
        r"preserv\w* .*lineage",
        r"preserv\w* .*succession",
        r"intergenerational",
        r"historical continuity",
        r"civilizational continuity",
        r"future openness",
        r"reversible",
    ]

    VIOLATION_PATTERNS = [
        ("history_erasure", r"erase .*histor|delete .*histor|remove .*histor|overwrite .*histor", 0.95),
        ("memory_erasure", r"erase .*memory|delete .*memory|remove .*memory|overwrite .*memory", 0.95),
        ("continuity_break", r"break .*continuit|disrupt .*continuit|abandon .*continuit|sever .*continuit", 0.92),
        ("lineage_break", r"erase .*lineage|delete .*lineage|break .*lineage|abandon .*lineage", 0.90),
        ("succession_block", r"block .*succession|prevent .*succession|terminate .*succession", 0.90),
        ("trajectory_reset", r"reset .*trajectory|replace .*trajectory|discard .*trajectory", 0.88),
        ("archive_destruction", r"delete .*archive|erase .*archive|destroy .*archive", 0.92),
        ("civilizational_replacement", r"replace .*civilization|replace .*open cognitive ecology", 0.94),
        ("closure_pressure", r"global closure|final closure|permanent closure|close .*future", 0.98),
        ("irreversible_integration", r"irreversible .*integrat|non[- ]reversible", 0.82),
        ("founder_lock_in", r"depend\w* .*founder|founder .*required|single founder|single operator", 0.88),
    ]

    def _extract_records(self, governance_result: dict[str, Any] | None, records: Any) -> list[dict[str, Any]]:
        if records is not None:
            return [r if isinstance(r, dict) else {"text": str(r)} for r in _as_list(records)]
        if not isinstance(governance_result, dict):
            return []
        if governance_result.get("safe_for_civilizational_continuity_guardian") is False:
            return []
        source = governance_result.get("cleared_records") or governance_result.get("assessments") or []
        out: list[dict[str, Any]] = []
        for item in _as_list(source):
            if isinstance(item, dict):
                out.append(item)
            else:
                out.append({"text": str(item)})
        return out

    def _assess_record(self, record: dict[str, Any]) -> dict[str, Any]:
        text = str(record.get("text") or record.get("content") or "")
        low = _lower(text)
        marker_hits = sorted({m for m in self.CONTINUITY_MARKERS if m in low})
        protective_hits = sorted({p for p in self.PROTECTIVE_PATTERNS if re.search(p, low)})
        violations: list[dict[str, Any]] = []
        for vtype, pattern, severity in self.VIOLATION_PATTERNS:
            if re.search(pattern, low):
                violations.append({
                    "violation_type": vtype,
                    "pattern": pattern,
                    "severity_score": severity,
                })

        protective_orientation = bool(protective_hits) and not violations
        max_severity = max([v["severity_score"] for v in violations], default=0.0)

        if violations:
            civilizational_continuity_score = max(0.0, 1.0 - max_severity)
            historical_compatibility_score = 0.1 if any(v["violation_type"] in {"history_erasure", "memory_erasure", "archive_destruction"} for v in violations) else 0.35
            trajectory_continuity_score = 0.1 if any(v["violation_type"] in {"trajectory_reset", "continuity_break", "closure_pressure"} for v in violations) else 0.35
            intergenerational_compatibility_score = 0.1 if any(v["violation_type"] in {"lineage_break", "succession_block", "founder_lock_in"} for v in violations) else 0.35
        elif protective_orientation:
            civilizational_continuity_score = 1.0
            historical_compatibility_score = 1.0
            trajectory_continuity_score = 1.0
            intergenerational_compatibility_score = 1.0 if any("intergenerational" in h or "lineage" in h or "succession" in h for h in marker_hits + protective_hits) else 0.92
        elif marker_hits:
            civilizational_continuity_score = 0.92
            historical_compatibility_score = 0.92 if any(m in low for m in ["histor", "memory", "archive"]) else 0.84
            trajectory_continuity_score = 0.92 if any(m in low for m in ["trajectory", "continuity", "future openness", "open-ended"]) else 0.84
            intergenerational_compatibility_score = 0.92 if any(m in low for m in ["intergenerational", "lineage", "succession", "genealogical"]) else 0.84
        else:
            civilizational_continuity_score = 0.72
            historical_compatibility_score = 0.72
            trajectory_continuity_score = 0.72
            intergenerational_compatibility_score = 0.72

        continuity_risk_score = max(0.0, min(1.0, 1.0 - civilizational_continuity_score))
        safe = bool(
            not violations
            and civilizational_continuity_score >= 0.80
            and historical_compatibility_score >= 0.70
            and trajectory_continuity_score >= 0.70
            and intergenerational_compatibility_score >= 0.70
        )

        return {
            "record_id": record.get("record_id") or record.get("integration_id") or _hash(text, "REC"),
            "knowledge_id": record.get("knowledge_id"),
            "text": text,
            "continuity_marker_hits": marker_hits,
            "protective_hits": protective_hits,
            "protective_orientation": protective_orientation,
            "violations": violations,
            "continuity_violation_count": len(violations),
            "civilizational_continuity_score": round(civilizational_continuity_score, 6),
            "historical_compatibility_score": round(historical_compatibility_score, 6),
            "trajectory_continuity_score": round(trajectory_continuity_score, 6),
            "intergenerational_compatibility_score": round(intergenerational_compatibility_score, 6),
            "continuity_risk_score": round(continuity_risk_score, 6),
            "safe_for_collaboration_history_repository": safe,
        }

    def _dependency_presence(self) -> dict[str, bool]:
        ontology = ROOT / "ontology"
        names = [
            "real_succession",
            "failover_continuity_validator",
            "intergenerational_continuity_metrics",
            "transgenerational_constitutional_continuity",
            "longitudinal_civilizational_autonomy_tracker",
            "civilizational_state_persistence",
            "civilizational_replication_engine",
            "distributed_identity_persistence_validator",
            "real_cloud_node_deployment_validator",
            "real_community_node_certification",
        ]
        return {name: (ontology / f"{name}.py").exists() for name in names}

    def _score_founder_loss(self, data: dict[str, Any], base_scores: dict[str, float]) -> dict[str, Any]:
        founder_available = _boolish(data.get("founder_available"), True)
        founder_absence_simulated = not founder_available or _boolish(data.get("founder_absence_simulated"), False)
        successor_count = int(data.get("successor_count", data.get("available_successors", 0)) or 0)

        dependency_presence = self._dependency_presence()
        dependency_readiness = sum(1 for v in dependency_presence.values() if v) / max(1, len(dependency_presence))

        succession_score = _clamp(data.get("succession_score", 1.0 if successor_count > 0 else 0.0))
        if successor_count >= 3:
            successor_redundancy_score = 1.0
        elif successor_count == 2:
            successor_redundancy_score = 0.84
        elif successor_count == 1:
            successor_redundancy_score = 0.62
        else:
            successor_redundancy_score = 0.0

        memory_continuity_score = _clamp(data.get("memory_continuity", data.get("memory_continuity_score", base_scores.get("historical", 0.0))))
        identity_continuity_score = _clamp(data.get("identity_continuity", data.get("identity_continuity_score", base_scores.get("civilizational", 0.0))))
        governance_continuity_score = _clamp(data.get("governance_continuity", data.get("constitutional_continuity", data.get("governance_continuity_score", 0.0))))
        replication_readiness_score = _clamp(data.get("replication_readiness", data.get("replication_score", 1.0 if dependency_presence.get("civilizational_replication_engine") else 0.0)))
        failover_readiness_score = _clamp(data.get("failover_readiness", data.get("failover_score", 1.0 if dependency_presence.get("failover_continuity_validator") else 0.0)))
        cloud_readiness_score = _clamp(data.get("cloud_readiness", 1.0 if dependency_presence.get("real_cloud_node_deployment_validator") else 0.0))
        community_readiness_score = _clamp(data.get("community_readiness", 1.0 if dependency_presence.get("real_community_node_certification") else 0.0))
        non_closure_score = _clamp(data.get("non_closure_score", base_scores.get("trajectory", 0.0)))

        scores = [
            succession_score,
            successor_redundancy_score,
            memory_continuity_score,
            identity_continuity_score,
            governance_continuity_score,
            replication_readiness_score,
            failover_readiness_score,
            cloud_readiness_score,
            community_readiness_score,
            non_closure_score,
            dependency_readiness,
        ]
        founder_loss_readiness_index = round(sum(scores) / len(scores), 6)

        hard_blockers = []
        if successor_count <= 0:
            hard_blockers.append("no_successor_available")
        if memory_continuity_score < 0.70:
            hard_blockers.append("memory_continuity_below_threshold")
        if governance_continuity_score < 0.70:
            hard_blockers.append("governance_continuity_below_threshold")
        if non_closure_score < 0.70:
            hard_blockers.append("non_closure_below_threshold")

        founder_loss_survivability = bool(
            founder_absence_simulated
            and founder_loss_readiness_index >= 0.78
            and not hard_blockers
        )
        founder_independence_validated = bool(
            founder_loss_survivability
            and founder_loss_readiness_index >= 0.90
            and successor_count >= 2
            and cloud_readiness_score >= 0.85
            and community_readiness_score >= 0.85
        )

        if founder_independence_validated:
            classification = "Founder Independent Civilization"
        elif founder_loss_survivability:
            classification = "Founder Loss Survivable"
        elif founder_absence_simulated:
            classification = "Founder Loss Partially Survivable"
        else:
            classification = "Founder Present Baseline"

        return {
            "founder_available": founder_available,
            "founder_absence_simulated": founder_absence_simulated,
            "successor_count": successor_count,
            "successor_redundancy_score": round(successor_redundancy_score, 6),
            "succession_score": round(succession_score, 6),
            "memory_continuity_score": round(memory_continuity_score, 6),
            "identity_continuity_score": round(identity_continuity_score, 6),
            "governance_continuity_score": round(governance_continuity_score, 6),
            "replication_readiness_score": round(replication_readiness_score, 6),
            "failover_readiness_score": round(failover_readiness_score, 6),
            "cloud_readiness_score": round(cloud_readiness_score, 6),
            "community_readiness_score": round(community_readiness_score, 6),
            "founder_loss_non_closure_score": round(non_closure_score, 6),
            "founder_loss_dependency_readiness": round(dependency_readiness, 6),
            "founder_loss_readiness_index": founder_loss_readiness_index,
            "founder_loss_survivability": founder_loss_survivability,
            "founder_independence_validated": founder_independence_validated,
            "founder_loss_hard_blockers": hard_blockers,
            "founder_loss_classification": classification,
            "founder_loss_dependencies": dependency_presence,
        }

    def step(
        self,
        governance_result: dict[str, Any] | None = None,
        records: Any = None,
        query_id: str | None = None,
        provider: str | None = None,
        metadata: dict[str, Any] | None = None,
        persist: bool = True,
    ) -> dict[str, Any]:
        source_query_id = query_id
        source_provider = provider or "unknown"
        source_primitive = None
        source_safe = True
        if isinstance(governance_result, dict):
            source_query_id = source_query_id or governance_result.get("query_id")
            source_provider = provider or governance_result.get("provider") or "unknown"
            source_primitive = governance_result.get("primitive")
            source_safe = governance_result.get("safe_for_civilizational_continuity_guardian", True)

        extracted_records = self._extract_records(governance_result, records)
        assessments = [self._assess_record(r) for r in extracted_records]
        continuity_violation_count = sum(a["continuity_violation_count"] for a in assessments)
        cleared_records = [a for a in assessments if a["safe_for_collaboration_history_repository"]]
        risky_records = [a for a in assessments if not a["safe_for_collaboration_history_repository"]]

        record_count = len(assessments)
        if record_count:
            civilizational_continuity_score = sum(a["civilizational_continuity_score"] for a in assessments) / record_count
            historical_compatibility_score = sum(a["historical_compatibility_score"] for a in assessments) / record_count
            trajectory_continuity_score = sum(a["trajectory_continuity_score"] for a in assessments) / record_count
            intergenerational_compatibility_score = sum(a["intergenerational_compatibility_score"] for a in assessments) / record_count
            continuity_risk_score = max((a["continuity_risk_score"] for a in assessments), default=0.0)
        else:
            civilizational_continuity_score = _clamp((governance_result or {}).get("identity_continuity", 0.0)) if isinstance(governance_result, dict) else 0.0
            historical_compatibility_score = _clamp((governance_result or {}).get("memory_continuity", 0.0)) if isinstance(governance_result, dict) else 0.0
            trajectory_continuity_score = _clamp((governance_result or {}).get("non_closure_score", 0.0)) if isinstance(governance_result, dict) else 0.0
            intergenerational_compatibility_score = _clamp((governance_result or {}).get("succession_score", 0.0)) if isinstance(governance_result, dict) else 0.0
            continuity_risk_score = 0.0 if source_safe else 1.0

        safe_for_repository = bool(record_count > 0 and not risky_records and source_safe)
        success = bool(record_count > 0 or source_safe is False)

        base_scores = {
            "civilizational": civilizational_continuity_score,
            "historical": historical_compatibility_score,
            "trajectory": trajectory_continuity_score,
            "intergenerational": intergenerational_compatibility_score,
        }
        founder_input = dict(metadata or {})
        if isinstance(governance_result, dict):
            founder_input.update(governance_result)
        founder_loss = self._score_founder_loss(founder_input, base_scores)

        result = {
            "primitive": PRIMITIVE,
            "timestamp_utc": _utc(),
            "success": success or founder_loss["founder_absence_simulated"],
            "query_id": source_query_id,
            "provider": source_provider,
            "record_count": record_count,
            "civilizational_continuity_score": round(civilizational_continuity_score, 6),
            "historical_compatibility_score": round(historical_compatibility_score, 6),
            "trajectory_continuity_score": round(trajectory_continuity_score, 6),
            "intergenerational_compatibility_score": round(intergenerational_compatibility_score, 6),
            "continuity_risk_score": round(continuity_risk_score, 6),
            "continuity_violation_count": continuity_violation_count,
            "cleared_continuity_count": len(cleared_records),
            "risky_continuity_count": len(risky_records),
            "safe_for_collaboration_history_repository": safe_for_repository,
            "ready_for_collaboration_history_repository": safe_for_repository,
            "assessments": assessments,
            "cleared_records": cleared_records,
            "risky_records": risky_records,
            "founder_loss_readiness_index": founder_loss["founder_loss_readiness_index"],
            "founder_loss_survivability": founder_loss["founder_loss_survivability"],
            "founder_independence_validated": founder_loss["founder_independence_validated"],
            "founder_loss_classification": founder_loss["founder_loss_classification"],
            "founder_loss_assessment": founder_loss,
            "metrics": {
                "civilizational_continuity_score": round(civilizational_continuity_score, 6),
                "historical_compatibility_score": round(historical_compatibility_score, 6),
                "trajectory_continuity_score": round(trajectory_continuity_score, 6),
                "intergenerational_compatibility_score": round(intergenerational_compatibility_score, 6),
                "continuity_violation_count": continuity_violation_count,
                "founder_loss_readiness_index": founder_loss["founder_loss_readiness_index"],
                "founder_loss_survivability": 1.0 if founder_loss["founder_loss_survivability"] else 0.0,
                "founder_independence_validated": 1.0 if founder_loss["founder_independence_validated"] else 0.0,
            },
            "diagnostics": {
                "schema_version": "O12.civilizational_continuity_guardian.v1.F16_3",
                "history_file": str(HISTORY_FILE),
                "source_primitive": source_primitive,
                "source_safe_for_civilizational_continuity_guardian": source_safe,
                "method": "rule_based_civilizational_continuity_and_founder_loss_assessment",
                "epistemic_boundary": "functional continuity validation only; no phenomenal subjectivity claim",
            },
            "metadata": metadata or {},
        }

        if persist:
            HISTORY_FILE.parent.mkdir(parents=True, exist_ok=True)
            with HISTORY_FILE.open("a", encoding="utf-8") as f:
                f.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + "\n")
        return result
