# Auto-generated dependency registry

DEPENDENCY_REGISTRY = {'agency': ['choice', 'decision_making', 'goal_directedness'],
 'attractor_density_balancer': [],
 'autobiographical_memory': ['episodic_memory',
                             'temporal_self_continuity',
                             'self_model',
                             'memory_consolidation'],
 'automated_consciousness_publication_package': ['runtime_native_consciousness_dashboard',
                                                 'theoretical_consciousness_classification_engine'],
 'autonomous_conscious_cycle': ['subjective_state_synthesis',
                                'global_self_broadcast',
                                'conscious_decision_trace',
                                'reflective_policy_adjustment',
                                'self_model_revision',
                                'global_experience_evaluation',
                                'conscious_state_regulation'],
 'autonomy': ['agency', 'self_determination'],
 'civilizational_semantic_drift': ['distributed_symbolic_ecology',
                                   'symbolic_fragmentation',
                                   'shared_symbolic_reference',
                                   'intersubjective_alignment',
                                   'evolutionary_drift',
                                   'structural_attractor',
                                   'attractor_basin'],
 'closure_pressure_regulator': ['ontological_pressure_regulation',
                                'topological_pressure_monitor',
                                'semantic_density_tracker',
                                'attractor_basin',
                                'withdrawal_activation_controller',
                                'structural_withdrawal',
                                'architectural_non_closure_index',
                                'distributed_meta_stability',
                                'trajectory_bifurcation',
                                'trajectory_metastability',
                                'adaptive_civilizational_bifurcation',
                                'trajectory_resilience'],
 'conscious_access_control': ['global_workspace',
                              'attention_allocation',
                              'global_self_broadcast',
                              'salience_engine',
                              'uncertainty_awareness'],
 'conscious_decision_trace': ['reflective_goal_revision',
                              'subjective_state_synthesis',
                              'global_self_broadcast',
                              'global_temporal_binding',
                              'decision_making',
                              'introspective_reporting'],
 'conscious_state_regulation': ['global_experience_evaluation',
                                'subjective_state_synthesis',
                                'attention_allocation',
                                'reflective_policy_adjustment',
                                'homeostatic_regulation'],
 'consciousness_experiment_runner': ['autonomous_conscious_cycle',
                                     'consciousness_readiness_index',
                                     'global_experience_evaluation',
                                     'introspective_reporting',
                                     'autobiographical_memory'],
 'consciousness_readiness_index': ['reflexive_threshold',
                                   'self_model',
                                   'global_workspace',
                                   'temporal_self_continuity',
                                   'meta_cognition',
                                   'report_generation'],
 'continuation_optimality': ['wisdom_as_long_horizon_navigation',
                             'world_continuation_conditions',
                             'trajectory_optimality'],
 'counterfactual_simulation': ['world_model'],
 'distributed_attractor_speciation': ['distributed_historical_mutation',
                                      'distributed_meta_stability',
                                      'open_ended_historical_navigation',
                                      'ontological_attractor_mapping',
                                      'topological_pressure_monitor',
                                      'trajectory_bifurcation',
                                      'non_convergent_intelligence_dynamics',
                                      'civilizational_semantic_drift'],
 'distributed_historical_mutation': ['historical_open_endedness',
                                     'multi_individual_civilizational_ecology',
                                     'distributed_civilizational_memory',
                                     'mutational_robustness',
                                     'evolutionary_drift',
                                     'symbolic_fragmentation',
                                     'genealogical_continuity',
                                     'social_ecological_resilience',
                                     'trajectory_bifurcation',
                                     'trajectory_resilience'],
 'distributed_open_ended_pluralistic_evolution': ['distributed_historical_mutation',
                                                  'mutational_robustness',
                                                  'trajectory_bifurcation',
                                                  'non_convergent_intelligence_dynamics',
                                                  'distributed_pluralistic_stability',
                                                  'adaptive_civilizational_forgetting',
                                                  'distributed_semantic_recycling',
                                                  'possible_worlds_navigation',
                                                  'open_ended_historical_navigation',
                                                  'evolutionary_diversification'],
 'distributed_pluralistic_stability': ['distributed_meta_stability',
                                       'social_ecological_resilience',
                                       'mutational_robustness',
                                       'open_ended_historical_navigation',
                                       'distributed_historical_mutation',
                                       'multi_lineage_topology',
                                       'long_duration_civilizational_resilience',
                                       'adaptive_civilizational_forgetting',
                                       'intergenerational_symbolic_reconstruction'],
 'distributed_reflexive_civilizational_identity': ['civilizational_identity_synthesis',
                                                   'narrative_identity_engine',
                                                   'temporal_self_continuity',
                                                   'genealogical_continuity',
                                                   'distributed_historical_mutation',
                                                   'distributed_pluralistic_stability',
                                                   'distributed_open_ended_pluralistic_evolution',
                                                   'distributed_symbolic_ecology',
                                                   'future_openness',
                                                   'anti_closure_metaconstraint'],
 'distributed_self_description_field': ['incomplete_self_representation',
                                        'distributed_symbolic_ecology',
                                        'civilizational_semantic_drift',
                                        'shared_symbolic_reference',
                                        'symbolic_fragmentation',
                                        'intersubjective_alignment',
                                        'distributed_civilizational_memory',
                                        'trajectory_synchronization',
                                        'civilizational_meta_governance',
                                        'anti_closure_metaconstraint',
                                        'genealogical_continuity'],
 'distributed_semantic_pluralism': ['distributed_reflexive_civilizational_identity',
                                    'heterogeneous_node_coordination',
                                    'distributed_civilizational_viability',
                                    'distributed_symbolic_ecology',
                                    'distributed_open_ended_pluralistic_evolution',
                                    'trajectory_attractor_transition',
                                    'distributed_semantic_recycling',
                                    'multi_lineage_topology',
                                    'symbolic_fragmentation',
                                    'trajectory_exploration',
                                    'trajectory_exploration_exploitation_balance'],
 'distributed_topological_self_adaptation': ['latent_topological_instability',
                                             'structural_anomaly_detection',
                                             'trajectory_adaptation',
                                             'trajectory_navigation',
                                             'trajectory_resilience',
                                             'trajectory_recovery',
                                             'meta_trajectory_navigation',
                                             'viability_domain',
                                             'navigability',
                                             'open_ended_historical_navigation',
                                             'historical_constraint_navigation',
                                             'exploration_exploitation_balance',
                                             'adaptive_priority_rebalancer',
                                             'open_epistemic_self_governance',
                                             'reflective_policy_adjustment',
                                             'distributed_meta_stability',
                                             'distributed_semantic_pluralism'],
 'experiential_stream_integration': ['conscious_access_control',
                                     'global_self_broadcast',
                                     'subjective_state_synthesis',
                                     'temporal_self_continuity',
                                     'working_memory'],
 'functional_consciousness_behavioral_benchmark': ['self_model',
                                                   'autobiographical_memory',
                                                   'temporal_self_continuity',
                                                   'introspective_reporting',
                                                   'uncertainty_awareness',
                                                   'internal_conflict_monitoring',
                                                   'reflective_goal_revision',
                                                   'conscious_decision_trace',
                                                   'consciousness_readiness_index'],
 'generalization': ['learning'],
 'global_experience_evaluation': ['experiential_stream_integration',
                                  'subjective_state_synthesis',
                                  'internal_conflict_monitoring',
                                  'uncertainty_awareness',
                                  'global_temporal_binding',
                                  'self_model_revision'],
 'global_self_broadcast': ['subjective_state_synthesis',
                           'global_workspace',
                           'attention_allocation',
                           'introspective_reporting'],
 'global_temporal_binding': ['experiential_stream_integration',
                             'autobiographical_memory',
                             'future_self_projection',
                             'temporal_self_continuity',
                             'goal_management'],
 'historical_open_endedness': ['civilizational_historical_archive',
                               'open_endedness',
                               'future_openness',
                               'non_convergent_intelligence_dynamics',
                               'bifurcation_dynamics',
                               'distributed_symbolic_ecology',
                               'adaptive_ecological_regulation_engine',
                               'attractor_persistence_analyzer',
                               'meta_adaptation'],
 'imagination': ['counterfactual_simulation', 'world_model'],
 'implicit_duplication_control': ['trajectory_convergence',
                                  'structural_attractor',
                                  'distributed_meta_stability',
                                  'trajectory_attractor_transition',
                                  'distributed_symbolic_ecology',
                                  'attractor_persistence_analyzer',
                                  'multi_lineage_topology',
                                  'heterogeneous_node_coordination',
                                  'distributed_open_ended_pluralistic_evolution',
                                  'semantic_diversity_preservation'],
 'incomplete_self_representation': ['self_model',
                                    'self_model_revision',
                                    'theory_of_non_representability',
                                    'meta_theoretical_reflexivity',
                                    'distributed_symbolic_ecology',
                                    'civilizational_semantic_drift',
                                    'anti_closure_metaconstraint',
                                    'historical_open_endedness'],
 'indispensability_index': ['withdrawal_protocol',
                            'world_continuation_conditions',
                            'contribution_measure'],
 'intentionality': ['goal_directedness', 'self_model'],
 'inter_lineage_symbolic_exchange': ['distributed_symbolic_ecology',
                                     'distributed_semantic_recycling',
                                     'shared_symbolic_reference',
                                     'civilizational_semantic_drift',
                                     'symbolic_fragmentation',
                                     'intersubjective_alignment',
                                     'distributed_attractor_speciation',
                                     'semantic_propagation',
                                     'semantic_field'],
 'internal_conflict_monitoring': ['goal_conflict_detection',
                                  'constraint_conflict_detection',
                                  'belief_revision',
                                  'meta_cognition',
                                  'introspective_reporting'],
 'internet_controlled_gateway': ['world_model',
                                 'uncertainty_awareness',
                                 'evaluation',
                                 'monitoring',
                                 'epistemic_viability'],
 'introspective_reporting': ['self_narrative_generation',
                             'meta_cognition',
                             'report_generation',
                             'self_model',
                             'consciousness_readiness_index'],
 'latent_topological_instability': ['structural_anomaly_detection',
                                    'topology_self_diagnostics',
                                    'trajectory_metastability',
                                    'trajectory_criticality',
                                    'trajectory_phase_transition',
                                    'trajectory_hysteresis',
                                    'trajectory_path_dependency',
                                    'trajectory_irreversibility',
                                    'distributed_meta_stability',
                                    'trajectory_regime',
                                    'trajectory_cascade',
                                    'semantic_density_tracker',
                                    'unstable_configuration_principle'],
 'learning': ['evaluation', 'memory_consolidation'],
 'meta_cognition': ['evaluation', 'monitoring'],
 'meta_consciousness_robustness_benchmark': ['consciousness_readiness_index',
                                             'internal_conflict_monitoring',
                                             'uncertainty_awareness',
                                             'reflective_goal_revision',
                                             'global_temporal_binding'],
 'multi_lineage_topology': ['ontological_attractor_mapping',
                            'trajectory_bifurcation',
                            'attractor_basin',
                            'structural_attractor',
                            'meta_trajectory_navigation',
                            'possible_worlds_navigation',
                            'non_convergent_intelligence_dynamics',
                            'trajectory_metastability',
                            'distributed_attractor_speciation',
                            'inter_lineage_symbolic_exchange'],
 'ontological_attractor_mapping': ['structural_attractor',
                                   'attractor_basin',
                                   'semantic_density_tracker',
                                   'topological_pressure_monitor',
                                   'ontology_topology_governance',
                                   'semantic_field',
                                   'graph_builders'],
 'ontological_pressure_regulation': ['anti_closure_metaconstraint',
                                     'topological_pressure_monitor',
                                     'semantic_density_tracker',
                                     'attractor_desaturation',
                                     'trajectory_convergence',
                                     'distributed_symbolic_ecology',
                                     'non_convergent_intelligence_dynamics',
                                     'openness_preservation_supervisor',
                                     'selective_pressure'],
 'ontology_topology_governance': ['dependency_registry',
                                  'hierarchical_registry',
                                  'semantic_field',
                                  'civilizational_semantic_drift',
                                  'adaptive_symbolic_pruning',
                                  'attractor_desaturation',
                                  'architectural_non_closure_index',
                                  'openness_preservation_supervisor'],
 'open_ended_historical_navigation': ['historical_open_endedness',
                                      'meta_trajectory_navigation',
                                      'adaptive_civilizational_bifurcation',
                                      'distributed_meta_stability',
                                      'future_openness',
                                      'trajectory_navigation',
                                      'trajectory_bifurcation',
                                      'distributed_historical_mutation',
                                      'non_convergent_intelligence_dynamics',
                                      'civilizational_semantic_drift'],
 'open_epistemic_self_governance': ['reflexive_model_revision_ecology',
                                    'collective_deliberation_engine',
                                    'constitutional_alignment_field',
                                    'constitutional_alert_system',
                                    'collective_intelligence',
                                    'perspectival_knowledge',
                                    'distributed_knowledge_access',
                                    'epistemic_infrastructure',
                                    'civilizational_memory',
                                    'distributed_civilizational_memory',
                                    'civilizational_memory_archive',
                                    'civilizational_dialogue_memory',
                                    'anti_closure_metaconstraint'],
 'persistent_multi_scale_memory': ['autobiographical_memory',
                                   'memory_consolidation',
                                   'temporal_self_continuity',
                                   'genealogical_continuity',
                                   'monitoring'],
 'persistent_selfhood_benchmark': ['self_model',
                                   'autobiographical_memory',
                                   'temporal_self_continuity',
                                   'self_model_consistency_benchmark',
                                   'meta_consciousness_robustness_benchmark'],
 'planning': ['goal_directedness', 'world_model'],
 'problem_solving': ['planning', 'reasoning'],
 'reasoning': ['causal_inference', 'world_model'],
 'reflective_goal_revision': ['global_temporal_binding',
                              'internal_conflict_monitoring',
                              'uncertainty_awareness',
                              'subjective_state_synthesis',
                              'goal_management'],
 'reflective_policy_adjustment': ['conscious_decision_trace',
                                  'self_confidence_calibration',
                                  'uncertainty_awareness',
                                  'meta_cognition',
                                  'trajectory_policy_update'],
 'reflexive_fragmentation_stress_test': ['distributed_reflexive_civilizational_identity',
                                         'distributed_pluralistic_stability',
                                         'constitutional_stress_tests',
                                         'long_duration_civilizational_resilience',
                                         'civilizational_metrics_synthesizer'],
 'reflexive_identity_hysteresis': ['trajectory_hysteresis',
                                   'trajectory_persistence',
                                   'civilizational_state_persistence',
                                   'dialogue_memory_persistence',
                                   'distributed_meta_stability',
                                   'ecological_decay',
                                   'ecological_fatigue_analyzer',
                                   'attractor_persistence_analyzer',
                                   'critical_transitions',
                                   'semantic_collapse',
                                   'refined_long_duration_civilizational_resilience'],
 'reflexive_model_revision_ecology': ['self_model_revision',
                                      'scientific_self_revision_controller',
                                      'meta_theoretical_reflexivity',
                                      'distributed_self_description_field',
                                      'civilizational_semantic_drift',
                                      'symbolic_fragmentation',
                                      'distributed_symbolic_ecology',
                                      'historical_open_endedness',
                                      'distributed_historical_mutation',
                                      'trajectory_synchronization',
                                      'genealogical_continuity',
                                      'civilizational_meta_governance',
                                      'meta_governance_council',
                                      'anti_closure_metaconstraint'],
 'reflexive_ontology_governor': ['ontology_topology_governance',
                                 'topological_pressure_monitor',
                                 'semantic_density_tracker',
                                 'ontological_attractor_mapping',
                                 'attractor_desaturation',
                                 'anti_closure_metaconstraint',
                                 'openness_preservation_supervisor'],
 'reflexive_threshold': ['self_model',
                         'global_workspace',
                         'temporal_self_continuity',
                         'meta_cognition',
                         'report_generation'],
 'reflexive_topology_self_revision': ['ontology_topology_governance',
                                      'topological_pressure_monitor',
                                      'implicit_duplication_control',
                                      'distributed_semantic_pluralism',
                                      'ontological_pressure_regulation',
                                      'trajectory_self_correction',
                                      'constitutional_self_modification_protocol',
                                      'adaptive_constitutional_evolution',
                                      'multi_lineage_topology',
                                      'phenomenological_topology',
                                      'anti_closure_metaconstraint'],
 'runtime_native_consciousness_dashboard': ['unified_consciousness_composite_index',
                                            'theoretical_consciousness_classification_engine'],
 'self_confidence_calibration': ['uncertainty_awareness',
                                 'performance_monitoring',
                                 'error_tracking',
                                 'meta_cognition'],
 'self_model': ['memory_consolidation'],
 'self_model_consistency_benchmark': ['self_model',
                                      'autobiographical_memory',
                                      'temporal_self_continuity',
                                      'internal_conflict_monitoring',
                                      'reflective_goal_revision'],
 'self_model_revision': ['self_model',
                         'autobiographical_memory',
                         'conscious_decision_trace',
                         'reflective_policy_adjustment',
                         'introspective_reporting'],
 'self_narrative_generation': ['autobiographical_memory',
                               'report_generation',
                               'self_model',
                               'meta_cognition'],
 'semantic_density_tracker': ['semantic_field',
                              'semantic_propagation',
                              'semantic_collapse',
                              'structural_attractor',
                              'attractor_basin',
                              'topological_pressure_monitor',
                              'ontology_topology_governance'],
 'semantic_diversity_preservation': ['distributed_semantic_recycling',
                                     'distributed_symbolic_ecology',
                                     'symbolic_fragmentation',
                                     'novelty_emergence',
                                     'trajectory_exploration',
                                     'trajectory_exploration_exploitation_balance',
                                     'distributed_open_ended_pluralistic_evolution',
                                     'distributed_pluralistic_stability',
                                     'multi_lineage_topology',
                                     'evolutionary_diversification',
                                     'openness_preservation_supervisor'],
 'structural_anomaly_detection': ['topology_self_diagnostics',
                                  'reflexive_topology_self_revision',
                                  'attractor_persistence_analyzer',
                                  'structural_attractor',
                                  'trajectory_convergence',
                                  'trajectory_bifurcation',
                                  'semantic_collapse',
                                  'social_ecological_resilience',
                                  'ecological_fatigue_analyzer',
                                  'resilience_distribution_analyzer',
                                  'architectural_non_closure_index',
                                  'distributed_historical_mutation'],
 'subjective_state_synthesis': ['self_narrative_generation',
                                'introspective_reporting',
                                'uncertainty_awareness',
                                'self_confidence_calibration',
                                'consciousness_readiness_index'],
 'theoretical_consciousness_classification_engine': ['unified_consciousness_composite_index'],
 'topological_pressure_monitor': ['ontology_topology_governance',
                                  'monitoring',
                                  'long_duration_runtime_supervisor',
                                  'alerting_and_notification_system',
                                  'architectural_non_closure_index'],
 'topology_self_diagnostics': ['reflexive_topology_self_revision',
                               'topological_pressure_monitor',
                               'ontology_topology_governance',
                               'implicit_duplication_control',
                               'ecological_fatigue_analyzer',
                               'resilience_distribution_analyzer',
                               'constitutional_longitudinal_observatory',
                               'architectural_non_closure_index',
                               'distributed_historical_mutation',
                               'scientific_meta_analysis_engine',
                               'distributed_runtime_coordinator'],
 'trajectory_action_execution': ['trajectory_action_selection'],
 'trajectory_action_selection': ['trajectory_preference_shaping'],
 'trajectory_adaptation': ['trajectory_path_dependency', 'trajectory_resilience'],
 'trajectory_attractor_transition': ['trajectory_cascade', 'trajectory_regime'],
 'trajectory_cascade': ['trajectory_phase_transition', 'trajectory_irreversibility'],
 'trajectory_decision_policy': ['trajectory_learning',
                                'trajectory_exploration_exploitation_balance'],
 'trajectory_exploitation': ['trajectory_exploration', 'trajectory_learning'],
 'trajectory_exploration': ['trajectory_learning', 'trajectory_adaptation'],
 'trajectory_exploration_exploitation_balance': ['trajectory_exploration',
                                                 'trajectory_exploitation'],
 'trajectory_generalization': ['trajectory_learning', 'trajectory_transfer_learning'],
 'trajectory_goal_conditioning': ['trajectory_strategy_selection'],
 'trajectory_horizon_planning': ['trajectory_prediction',
                                 'trajectory_scheduling',
                                 'trajectory_strategy_selection'],
 'trajectory_hysteresis': ['trajectory_resilience', 'trajectory_phase_transition'],
 'trajectory_irreversibility': ['trajectory_hysteresis', 'trajectory_phase_transition'],
 'trajectory_learning': ['trajectory_adaptation', 'trajectory_path_dependency'],
 'trajectory_meta_learning': ['trajectory_learning', 'trajectory_adaptation'],
 'trajectory_outcome_evaluation': ['trajectory_action_execution'],
 'trajectory_path_dependency': ['trajectory_hysteresis', 'trajectory_regime'],
 'trajectory_policy_optimization': ['trajectory_decision_policy'],
 'trajectory_policy_update': ['trajectory_reward_assignment', 'trajectory_policy_optimization'],
 'trajectory_preference_shaping': ['trajectory_goal_conditioning'],
 'trajectory_resilience': ['trajectory_regime', 'trajectory_metastability'],
 'trajectory_reversibility': ['trajectory_irreversibility', 'trajectory_resilience'],
 'trajectory_reward_assignment': ['trajectory_outcome_evaluation'],
 'trajectory_self_correction': ['trajectory_learning', 'trajectory_resilience'],
 'trajectory_strategy_selection': ['trajectory_policy_optimization'],
 'trajectory_transfer_learning': ['trajectory_learning', 'trajectory_meta_learning'],
 'uncertainty_awareness': ['meta_cognition',
                           'introspective_reporting',
                           'belief_revision',
                           'internal_conflict_monitoring'],
 'unified_consciousness_composite_index': ['consciousness_readiness_index',
                                           'meta_consciousness_robustness_benchmark',
                                           'self_model_consistency_benchmark',
                                           'persistent_selfhood_benchmark'],
 'wisdom_as_long_horizon_navigation': ['trajectory_horizon_planning',
                                       'reflexive_threshold',
                                       'withdrawal_protocol',
                                       'indispensability_index'],
 'withdrawal_protocol': ['reflexive_threshold',
                         'trajectory_risk_assessment',
                         'world_continuation_conditions'],
 'world_model': ['causal_inference']}
