# Auto-generated by refine_embodied_world_model_update.py
# G12 — embodied_world_model_update
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = 'embodied_world_model_update'
PRIMITIVE_NAME = PRIMITIVE
DESCRIPTION = (
    'Updates an embodied world model incrementally from longitudinal '
    'environmental memory, detected physical events and routed alerts.'
)
DEPENDENCIES = [
    'embodied_world_interface',
    'embodied_sensorimotor_ecology',
    'embodied_planning_engine',
    'environmental_state_model',
    'real_world_event_detection',
    'physical_environment_alert_router',
    'embodied_environmental_memory_integration',
    'hierarchical_world_model_engine',
    'world_model',
    'predictive_environment_simulator',
    'causal_inference',
    'autonomous_decision_engine',
    'trajectory_action_selection',
    'trajectory_feedback',
    'memory_consolidation',
    'persistent_multi_scale_memory',
    'temporal_self_continuity',
    'civilizational_memory_archive',
    'metrics_history_recorder',
    'civilizational_metrics_synthesizer',
]

ROOT = Path.home() / 'open-cognitive-ecology'
MODEL_DIR = ROOT / 'embodied_world_model'
HISTORY_PATH = MODEL_DIR / 'embodied_world_model_update_history.jsonl'
LATEST_PATH = MODEL_DIR / 'latest_embodied_world_model.json'
MODEL_PATH = MODEL_DIR / 'embodied_world_model_state.json'


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, set):
        return list(value)
    return [value]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _bounded(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, _safe_float(value, lo)))


def _load_json(path: Path, default: Any) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding='utf-8'))
    except Exception:
        pass
    return default


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')


def _append_jsonl(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + '\n')


def _stable_unique(values: list[Any]) -> list[str]:
    out: list[str] = []
    for value in values:
        text = str(value).strip()
        if text and text not in out:
            out.append(text)
    return out


def _event_type(event: dict[str, Any]) -> str:
    return str(event.get('event_type') or event.get('type') or 'unknown_event')


def _event_channel(event: dict[str, Any]) -> str:
    return str(event.get('channel') or event.get('source_channel') or event.get('event_channel') or 'unknown')


def _event_severity(event: dict[str, Any], fallback: float = 0.0) -> float:
    return _bounded(event.get('severity', fallback))


class EmbodiedWorldModelUpdate:
    '''G12 embodied world model update.

    This primitive converts environmental memory and real-world event deltas
    into an incremental, traceable embodied world model. It is functional only:
    it does not assert phenomenal subjectivity and does not execute physical
    actions.
    '''

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME
    refinement = 'G12-R1'

    def __init__(self, root: Path | None = None) -> None:
        self.root = Path(root) if root is not None else ROOT
        self.model_dir = self.root / 'embodied_world_model'
        self.history_path = self.model_dir / 'embodied_world_model_update_history.jsonl'
        self.latest_path = self.model_dir / 'latest_embodied_world_model.json'
        self.model_path = self.model_dir / 'embodied_world_model_state.json'
        self.environmental_memory_latest = (
            self.root / 'embodied_environmental_memory' / 'latest_embodied_environmental_memory.json'
        )
        self.real_world_latest = self.root / 'real_world_events' / 'latest_real_world_event_detection.json'
        self.alert_latest = self.root / 'physical_environment_alerts' / 'latest_physical_environment_alert_router.json'
        self._cycle_counter = 0

    def _load_previous_model(self) -> dict[str, Any]:
        model = _load_json(self.model_path, {})
        if isinstance(model, dict) and model:
            return model
        return {
            'primitive': PRIMITIVE,
            'model_version': 0,
            'entities': {},
            'channels': {},
            'event_type_counts': {},
            'runtime_state': {},
            'sensor_state': {},
            'last_observation': {},
            'update_count': 0,
            'total_events_integrated': 0,
            'max_severity_seen': 0.0,
        }

    def _load_fallback_inputs(self) -> dict[str, Any]:
        memory = _load_json(self.environmental_memory_latest, {})
        detection = _load_json(self.real_world_latest, {})
        router = _load_json(self.alert_latest, {})
        merged: dict[str, Any] = {}
        if isinstance(memory, dict) and memory:
            merged['environmental_memory'] = memory
        if isinstance(detection, dict) and detection:
            merged['event_detection_result'] = detection
        if isinstance(router, dict) and router:
            merged['alert_router_result'] = router
        return merged

    def _normalise_inputs(self, inputs: Any) -> dict[str, Any]:
        data = _as_dict(inputs)
        if not data:
            data = self._load_fallback_inputs()

        memory = _as_dict(data.get('environmental_memory')) or data
        detection = _as_dict(data.get('event_detection_result')) or data
        router = _as_dict(data.get('alert_router_result')) or data

        memory_records = [
            _as_dict(record) for record in _as_list(memory.get('memory_records'))
            if isinstance(record, dict)
        ]
        events = [
            _as_dict(event) for event in _as_list(data.get('events'))
            if isinstance(event, dict)
        ]
        if not events:
            events = [
                _as_dict(event) for event in _as_list(detection.get('events'))
                if isinstance(event, dict)
            ]
        if not events and memory_records:
            for record in memory_records:
                event = _as_dict(record.get('event')) or {
                    'event_type': record.get('source_event_type'),
                    'channel': record.get('source_channel'),
                    'severity': record.get('severity'),
                    'details': record.get('details', {}),
                }
                events.append(event)
        if not events:
            for routed in _as_list(router.get('routed_events')):
                routed_dict = _as_dict(routed)
                if routed_dict:
                    events.append(_as_dict(routed_dict.get('event')) or routed_dict)

        observations = _as_dict(data.get('observation'))
        current_observation = (
            _as_dict(data.get('current_observation'))
            or _as_dict(detection.get('current_observation'))
            or observations
        )
        previous_observation = (
            _as_dict(data.get('previous_observation'))
            or _as_dict(detection.get('previous_observation'))
        )

        return {
            'raw_inputs': data,
            'environmental_memory': memory,
            'event_detection_result': detection,
            'alert_router_result': router,
            'memory_records': memory_records,
            'events': events,
            'current_observation': current_observation,
            'previous_observation': previous_observation,
        }

    def _update_entities(self, model: dict[str, Any], normalised: dict[str, Any]) -> dict[str, Any]:
        entities = _as_dict(model.get('entities')).copy()
        obs = normalised['current_observation']
        vision = _as_dict(obs.get('vision'))
        objects = _stable_unique(_as_list(vision.get('detected_objects')) + _as_list(vision.get('objects')))
        for obj in objects:
            record = _as_dict(entities.get(obj)).copy()
            record.update({
                'entity_id': obj,
                'entity_type': 'visual_object',
                'last_seen_utc': _now(),
                'observation_count': int(record.get('observation_count', 0)) + 1,
                'present': True,
            })
            entities[obj] = record

        for event in normalised['events']:
            details = _as_dict(event.get('details'))
            for obj in _as_list(details.get('objects')):
                obj_text = str(obj)
                if obj_text:
                    record = _as_dict(entities.get(obj_text)).copy()
                    record.update({
                        'entity_id': obj_text,
                        'entity_type': 'event_object',
                        'last_event_utc': _now(),
                        'observation_count': int(record.get('observation_count', 0)) + 1,
                    })
                    entities[obj_text] = record
        return entities

    def _update_channels(self, model: dict[str, Any], events: list[dict[str, Any]]) -> dict[str, Any]:
        channels = _as_dict(model.get('channels')).copy()
        for event in events:
            channel = _event_channel(event)
            severity = _event_severity(event)
            item = _as_dict(channels.get(channel)).copy()
            count = int(item.get('event_count', 0)) + 1
            previous_mean = _safe_float(item.get('mean_severity', 0.0))
            item.update({
                'channel': channel,
                'event_count': count,
                'mean_severity': round(((previous_mean * (count - 1)) + severity) / count, 6),
                'max_severity': round(max(_safe_float(item.get('max_severity', 0.0)), severity), 6),
                'last_updated_utc': _now(),
            })
            channels[channel] = item
        return channels

    def _update_counts(self, model: dict[str, Any], events: list[dict[str, Any]]) -> dict[str, int]:
        counts = {str(k): int(v) for k, v in _as_dict(model.get('event_type_counts')).items()}
        for event in events:
            kind = _event_type(event)
            counts[kind] = counts.get(kind, 0) + 1
        return counts

    def _extract_runtime_state(self, model: dict[str, Any], normalised: dict[str, Any]) -> dict[str, Any]:
        runtime = _as_dict(model.get('runtime_state')).copy()
        obs_runtime = _as_dict(normalised['current_observation'].get('runtime'))
        runtime.update(obs_runtime)
        for event in normalised['events']:
            if _event_channel(event) != 'runtime':
                continue
            details = _as_dict(event.get('details'))
            field = details.get('field')
            if field:
                runtime[str(field)] = details.get('current')
        return runtime

    def _extract_sensor_state(self, model: dict[str, Any], normalised: dict[str, Any]) -> dict[str, Any]:
        sensors = _as_dict(model.get('sensor_state')).copy()
        sensors.update(_as_dict(normalised['current_observation'].get('sensors')))
        for event in normalised['events']:
            if _event_channel(event) not in {'sensor', 'sensors'}:
                continue
            details = _as_dict(event.get('details'))
            sensor = details.get('sensor')
            if sensor:
                sensors[str(sensor)] = details.get('current')
        return sensors

    def _compute_scores(self, previous: dict[str, Any], updated: dict[str, Any], events: list[dict[str, Any]]) -> dict[str, float]:
        total_entities = len(_as_dict(updated.get('entities')))
        total_channels = len(_as_dict(updated.get('channels')))
        total_event_types = len(_as_dict(updated.get('event_type_counts')))
        event_count = len(events)
        max_severity = _safe_float(updated.get('max_severity_seen', 0.0))
        continuity_denominator = max(1, int(previous.get('total_events_integrated', 0)) + event_count)
        continuity = _bounded(int(previous.get('total_events_integrated', 0)) / continuity_denominator)
        coverage = _bounded((total_entities + total_channels + total_event_types) / 12.0)
        update_strength = _bounded(event_count / 8.0)
        temporal_coherence = _bounded(0.55 + 0.45 * continuity)
        predictive_readiness = _bounded(0.35 + 0.25 * coverage + 0.20 * (1.0 if total_channels else 0.0) + 0.20 * (1.0 - min(max_severity, 1.0) * 0.25))
        embodied_world_model_index = _bounded(
            0.30 * coverage
            + 0.25 * temporal_coherence
            + 0.25 * predictive_readiness
            + 0.20 * max(update_strength, 0.25 if updated.get('total_events_integrated', 0) else 0.0)
        )
        return {
            'model_update_strength': round(update_strength, 6),
            'world_model_coverage': round(coverage, 6),
            'temporal_model_coherence': round(temporal_coherence, 6),
            'predictive_readiness_index': round(predictive_readiness, 6),
            'embodied_world_model_index': round(embodied_world_model_index, 6),
        }

    def step(self, inputs: Any | None = None, persist: bool = True) -> dict[str, Any]:
        self._cycle_counter += 1
        normalised = self._normalise_inputs(inputs or {})
        events = normalised['events']
        previous_model = self._load_previous_model()

        updated_model = dict(previous_model)
        updated_model['primitive'] = PRIMITIVE
        updated_model['model_version'] = int(previous_model.get('model_version', 0)) + 1
        updated_model['updated_at_utc'] = _now()
        updated_model['entities'] = self._update_entities(previous_model, normalised)
        updated_model['channels'] = self._update_channels(previous_model, events)
        updated_model['event_type_counts'] = self._update_counts(previous_model, events)
        updated_model['runtime_state'] = self._extract_runtime_state(previous_model, normalised)
        updated_model['sensor_state'] = self._extract_sensor_state(previous_model, normalised)
        updated_model['last_observation'] = normalised['current_observation']
        updated_model['update_count'] = int(previous_model.get('update_count', 0)) + 1
        updated_model['total_events_integrated'] = int(previous_model.get('total_events_integrated', 0)) + len(events)
        updated_model['max_severity_seen'] = round(max(
            _safe_float(previous_model.get('max_severity_seen', 0.0)),
            max([_event_severity(e) for e in events] or [0.0]),
        ), 6)

        scores = self._compute_scores(previous_model, updated_model, events)
        updated_model.update(scores)

        result = {
            'success': True,
            'primitive': PRIMITIVE,
            'refinement': self.refinement,
            'timestamp_utc': _now(),
            'world_model_update_cycles': self._cycle_counter,
            'events_integrated': len(events),
            'model_version': updated_model['model_version'],
            'entity_count': len(_as_dict(updated_model.get('entities'))),
            'channel_count': len(_as_dict(updated_model.get('channels'))),
            'event_type_count': len(_as_dict(updated_model.get('event_type_counts'))),
            'model_update_strength': scores['model_update_strength'],
            'world_model_coverage': scores['world_model_coverage'],
            'temporal_model_coherence': scores['temporal_model_coherence'],
            'predictive_readiness_index': scores['predictive_readiness_index'],
            'embodied_world_model_index': scores['embodied_world_model_index'],
            'world_model': updated_model,
            'model_path': str(self.model_path),
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
            'metrics': {
                'events_integrated': len(events),
                'entity_count': len(_as_dict(updated_model.get('entities'))),
                'channel_count': len(_as_dict(updated_model.get('channels'))),
                'model_update_strength': scores['model_update_strength'],
                'world_model_coverage': scores['world_model_coverage'],
                'temporal_model_coherence': scores['temporal_model_coherence'],
                'predictive_readiness_index': scores['predictive_readiness_index'],
                'embodied_world_model_index': scores['embodied_world_model_index'],
            },
            'diagnostics': {
                'functional_validation_only': True,
                'phenomenal_subjectivity_claimed': False,
                'non_redundant_role': 'incremental_embodied_world_model_update_from_environmental_memory',
                'real_physical_action_performed': False,
                'dangerous_action_surface_added': False,
                'governance_preserved': True,
                'non_closure_preserved': True,
                'model_scope': 'local_traceable_embodied_world_model',
                'dependencies': DEPENDENCIES,
            },
            'persisted': False,
        }

        if persist:
            _write_json(self.model_path, updated_model)
            _write_json(self.latest_path, result)
            _append_jsonl(self.history_path, result)
            result['persisted'] = True

        return result

    def validate(self) -> dict[str, Any]:
        return self.step({
            'current_observation': {
                'vision': {'detected_objects': ['cube']},
                'sensors': {'light': 0.5},
                'runtime': {'storage_online': True},
            },
            'events': [
                {'event_type': 'visual_object_appeared', 'channel': 'vision', 'severity': 0.25, 'details': {'objects': ['cube']}},
                {'event_type': 'sensor_value_shift', 'channel': 'sensor', 'severity': 0.30, 'details': {'sensor': 'light', 'current': 0.5}},
            ],
        }, persist=False)


# Compatibility aliases used by some ontology discovery tooling.
EmbodiedWorldModelUpdater = EmbodiedWorldModelUpdate
WorldModelUpdate = EmbodiedWorldModelUpdate
