# Auto-generated by refine_embodied_environmental_memory_integration.py
# G11 — embodied_environmental_memory_integration
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = 'embodied_environmental_memory_integration'
PRIMITIVE_NAME = PRIMITIVE
DESCRIPTION = (
    'Integrates routed physical and environmental events into a longitudinal '
    'embodied environmental memory with consolidation, retrieval and metrics.'
)
DEPENDENCIES = [
    'real_world_event_detection',
    'physical_environment_alert_router',
    'civilizational_memory',
    'civilizational_memory_archive',
    'conversation_memory_archive',
    'autobiographical_memory',
    'dialogue_memory_persistence',
    'memory_consolidation',
    'persistent_multi_scale_memory',
    'temporal_self_continuity',
    'life_history_synthesis_engine',
    'longitudinal_relationship_evolution_analyzer',
    'civilizational_state_persistence',
    'metrics_history_recorder',
    'civilizational_metrics_synthesizer',
    'intergenerational_continuity_metrics',
]

ROOT = Path.home() / 'open-cognitive-ecology'
MEMORY_DIR = ROOT / 'embodied_environmental_memory'
HISTORY_PATH = MEMORY_DIR / 'embodied_environmental_memory_history.jsonl'
LATEST_PATH = MEMORY_DIR / 'latest_embodied_environmental_memory.json'
INDEX_PATH = MEMORY_DIR / 'embodied_environmental_memory_index.json'
RETRIEVAL_PATH = MEMORY_DIR / 'embodied_environmental_memory_retrieval_index.json'


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, set):
        return list(value)
    return [value]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _bounded(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, _safe_float(value, lo)))


def _load_json(path: Path, default: Any) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding='utf-8'))
    except Exception:
        pass
    return default


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')


def _append_jsonl(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + '\n')


def _event_type(event: dict[str, Any]) -> str:
    return str(event.get('event_type') or event.get('type') or 'unknown_event')


def _event_channel(event: dict[str, Any]) -> str:
    return str(event.get('channel') or event.get('event_channel') or 'unknown')


def _event_severity(event: dict[str, Any], fallback: float = 0.0) -> float:
    return _bounded(event.get('severity', fallback))


def _stable_unique(values: list[str]) -> list[str]:
    out: list[str] = []
    for value in values:
        text = str(value).strip()
        if text and text not in out:
            out.append(text)
    return out


class EmbodiedEnvironmentalMemoryIntegration:
    """G11 embodied environmental memory integration.

    The primitive receives events from G9/G10, turns them into traceable
    environmental memory records, consolidates longitudinal indices and exposes
    a retrieval summary. It validates functional memory integration only and
    does not claim phenomenal subjectivity.
    """

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME
    refinement = 'G11-R1'

    def __init__(self, root: Path | None = None) -> None:
        self.root = Path(root) if root is not None else ROOT
        self.memory_dir = self.root / 'embodied_environmental_memory'
        self.history_path = self.memory_dir / 'embodied_environmental_memory_history.jsonl'
        self.latest_path = self.memory_dir / 'latest_embodied_environmental_memory.json'
        self.index_path = self.memory_dir / 'embodied_environmental_memory_index.json'
        self.retrieval_path = self.memory_dir / 'embodied_environmental_memory_retrieval_index.json'
        self._cycle_counter = 0

    def _load_latest_router(self) -> dict[str, Any]:
        candidates = [
            self.root / 'physical_environment_alerts' / 'latest_physical_environment_alert_router.json',
            self.root / 'real_world_events' / 'latest_real_world_event_detection.json',
        ]
        for candidate in candidates:
            data = _load_json(candidate, {})
            if isinstance(data, dict) and data:
                return data
        return {}

    def _normalise_inputs(self, inputs: Any) -> dict[str, Any]:
        data = _as_dict(inputs)
        if not data:
            data = self._load_latest_router()
        router_result = _as_dict(data.get('alert_router_result')) or data
        detection_result = _as_dict(data.get('event_detection_result')) or data

        routed_events = [
            _as_dict(event) for event in _as_list(router_result.get('routed_events'))
            if isinstance(event, dict)
        ]
        raw_events = [
            _as_dict(event) for event in _as_list(detection_result.get('events'))
            if isinstance(event, dict)
        ]

        if not raw_events:
            for routed in routed_events:
                embedded = _as_dict(routed.get('event'))
                raw_events.append(embedded or routed)

        return {
            'raw_inputs': data,
            'router_result': router_result,
            'detection_result': detection_result,
            'routed_events': routed_events,
            'events': raw_events,
        }

    def _build_memory_records(self, normalised: dict[str, Any]) -> list[dict[str, Any]]:
        records: list[dict[str, Any]] = []
        routed_events = normalised['routed_events']
        events = normalised['events']
        route_by_signature: dict[str, dict[str, Any]] = {}
        for routed in routed_events:
            signature = f"{_event_channel(routed)}::{_event_type(routed)}"
            route_by_signature[signature] = routed

        for index, event in enumerate(events):
            channel = _event_channel(event)
            event_type = _event_type(event)
            signature = f'{channel}::{event_type}'
            routed = route_by_signature.get(signature, {})
            routes = routed.get('routes') or []
            severity = _event_severity(event, routed.get('severity', 0.0))
            memory_id = f'EEM-{index + 1:04d}-{event_type}'
            record = {
                'memory_id': memory_id,
                'timestamp_utc': _now(),
                'source_event_type': event_type,
                'source_channel': channel,
                'severity': round(severity, 6),
                'routes': _stable_unique([str(route) for route in _as_list(routes)]),
                'memory_scope': self._memory_scope(channel, severity, routes),
                'event': event,
                'routed_event': routed,
                'retrieval_keys': self._retrieval_keys(event, routed),
            }
            records.append(record)
        return records

    def _memory_scope(self, channel: str, severity: float, routes: Any) -> str:
        route_set = set(str(route) for route in _as_list(routes))
        if 'governance' in route_set or severity >= 0.65:
            return 'governance_environmental_memory'
        if channel == 'runtime':
            return 'infrastructure_environmental_memory'
        if channel in {'vision', 'audio', 'sensor'}:
            return 'embodied_sensorial_memory'
        return 'general_environmental_memory'

    def _retrieval_keys(self, event: dict[str, Any], routed: dict[str, Any]) -> list[str]:
        keys = [
            _event_channel(event),
            _event_type(event),
            str(event.get('severity_class') or routed.get('severity_class') or ''),
        ]
        details = _as_dict(event.get('details'))
        for value in details.values():
            if isinstance(value, str):
                keys.append(value)
        return _stable_unique(keys)

    def _load_index(self) -> dict[str, Any]:
        return _load_json(self.index_path, {
            'primitive': PRIMITIVE,
            'total_cycles': 0,
            'total_memory_records': 0,
            'total_consolidated_events': 0,
            'channel_counts': {},
            'event_type_counts': {},
            'max_severity_seen': 0.0,
        })

    def _update_index(self, records: list[dict[str, Any]]) -> dict[str, Any]:
        index = self._load_index()
        index['total_cycles'] = int(index.get('total_cycles', 0)) + 1
        index['total_memory_records'] = int(index.get('total_memory_records', 0)) + len(records)
        index['total_consolidated_events'] = int(index.get('total_consolidated_events', 0)) + len(records)
        channel_counts = _as_dict(index.get('channel_counts'))
        event_type_counts = _as_dict(index.get('event_type_counts'))
        max_seen = _safe_float(index.get('max_severity_seen'), 0.0)
        for record in records:
            channel = str(record.get('source_channel', 'unknown'))
            event_type = str(record.get('source_event_type', 'unknown_event'))
            channel_counts[channel] = int(channel_counts.get(channel, 0)) + 1
            event_type_counts[event_type] = int(event_type_counts.get(event_type, 0)) + 1
            max_seen = max(max_seen, _safe_float(record.get('severity'), 0.0))
        index['channel_counts'] = channel_counts
        index['event_type_counts'] = event_type_counts
        index['max_severity_seen'] = round(max_seen, 6)
        index['latest_timestamp_utc'] = _now()
        index['latest_path'] = str(self.latest_path)
        return index

    def _retrieval_summary(self, records: list[dict[str, Any]], index: dict[str, Any]) -> dict[str, Any]:
        keys: list[str] = []
        for record in records:
            keys.extend([str(key) for key in _as_list(record.get('retrieval_keys'))])
        keys = _stable_unique(keys)
        channel_counts = _as_dict(index.get('channel_counts'))
        top_channels = sorted(channel_counts.items(), key=lambda item: (-int(item[1]), str(item[0])))[:5]
        return {
            'retrieval_ready': True,
            'retrieval_key_count': len(keys),
            'retrieval_keys': keys[:30],
            'top_channels': top_channels,
            'latest_memory_ids': [record.get('memory_id') for record in records[-10:]],
        }

    def _consolidation_score(self, records: list[dict[str, Any]], index: dict[str, Any]) -> float:
        if not records:
            return 0.0
        route_integrity = sum(1 for record in records if record.get('routes')) / max(1, len(records))
        retrieval_integrity = sum(1 for record in records if record.get('retrieval_keys')) / max(1, len(records))
        longitudinal_factor = min(1.0, int(index.get('total_cycles', 0)) / 10.0)
        severity_coverage = min(1.0, _safe_float(index.get('max_severity_seen'), 0.0) + 0.25)
        score = (route_integrity + retrieval_integrity + longitudinal_factor + severity_coverage) / 4.0
        return round(score, 6)

    def step(self, inputs: Any = None, persist: bool = True) -> dict[str, Any]:
        self._cycle_counter += 1
        normalised = self._normalise_inputs(inputs)
        records = self._build_memory_records(normalised)
        index = self._update_index(records)
        retrieval = self._retrieval_summary(records, index)
        consolidation_score = self._consolidation_score(records, index)
        severities = [_safe_float(record.get('severity'), 0.0) for record in records]
        mean_severity = sum(severities) / len(severities) if severities else 0.0
        channels = _stable_unique([str(record.get('source_channel', 'unknown')) for record in records])

        result = {
            'success': True,
            'primitive': PRIMITIVE,
            'refinement': 'G11-R1',
            'timestamp_utc': _now(),
            'environmental_memory_cycles': self._cycle_counter,
            'source_primitives': ['real_world_event_detection', 'physical_environment_alert_router'],
            'integrated_memory_records': len(records),
            'consolidated_event_count': len(records),
            'retrieval_ready': retrieval['retrieval_ready'],
            'retrieval_key_count': retrieval['retrieval_key_count'],
            'environmental_memory_consolidation_score': consolidation_score,
            'longitudinal_environmental_memory_index': round(min(1.0, int(index.get('total_memory_records', 0)) / 25.0), 6),
            'embodied_memory_continuity_index': round(min(1.0, (consolidation_score + min(1.0, int(index.get('total_cycles', 0)) / 10.0)) / 2.0), 6),
            'mean_event_severity_integrated': round(mean_severity, 6),
            'memory_channels': channels,
            'memory_records': records,
            'retrieval_summary': retrieval,
            'memory_index': index,
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
            'retrieval_path': str(self.retrieval_path),
            'metrics': {
                'integrated_memory_records': len(records),
                'consolidated_event_count': len(records),
                'environmental_memory_consolidation_score': consolidation_score,
                'longitudinal_environmental_memory_index': round(min(1.0, int(index.get('total_memory_records', 0)) / 25.0), 6),
                'embodied_memory_continuity_index': round(min(1.0, (consolidation_score + min(1.0, int(index.get('total_cycles', 0)) / 10.0)) / 2.0), 6),
                'retrieval_key_count': retrieval['retrieval_key_count'],
            },
            'diagnostics': {
                'functional_validation_only': True,
                'phenomenal_subjectivity_claimed': False,
                'non_redundant_role': 'integrate_routed_physical_events_into_longitudinal_embodied_environmental_memory',
                'real_physical_action_performed': False,
                'dangerous_action_surface_added': False,
                'governance_preserved': True,
                'non_closure_preserved': True,
                'storage_scope': 'local_traceable_environmental_memory_archive',
                'dependencies': list(DEPENDENCIES),
            },
            'persisted': bool(persist),
        }

        if persist:
            self._persist(result, index, retrieval)
        return result

    def _persist(self, result: dict[str, Any], index: dict[str, Any], retrieval: dict[str, Any]) -> None:
        self.memory_dir.mkdir(parents=True, exist_ok=True)
        _append_jsonl(self.history_path, result)
        _write_json(self.latest_path, result)
        _write_json(self.index_path, index)
        _write_json(self.retrieval_path, retrieval)

        if result.get('integrated_memory_records', 0) > 0:
            try:
                from ontology.civilizational_memory_archive import CivilizationalMemoryArchive
                archive = CivilizationalMemoryArchive(output_dir=self.root / 'civilizational_memory_archive')
                archive.archive(
                    category='embodied_environmental_memory',
                    payload={
                        'primitive': PRIMITIVE,
                        'timestamp_utc': result.get('timestamp_utc'),
                        'integrated_memory_records': result.get('integrated_memory_records'),
                        'environmental_memory_consolidation_score': result.get('environmental_memory_consolidation_score'),
                        'latest_path': result.get('latest_path'),
                    },
                )
            except Exception:
                pass


class EmbodiedEnvironmentalMemory(EmbodiedEnvironmentalMemoryIntegration):
    """Alias court tolérant pour usages futurs."""


__all__ = [
    'EmbodiedEnvironmentalMemoryIntegration',
    'EmbodiedEnvironmentalMemory',
    'PRIMITIVE',
    'DEPENDENCIES',
]
