# Auto-generated by refine_governance_consistency_checker.py
# O11 — governance_consistency_checker
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = "governance_consistency_checker"

DEPENDENCIES = [
    "identity_preservation_monitor",
    "constitutional_governance_supervisor",
    "constitutional_alert_system",
    "anti_closure_metaconstraint",
    "openness_preservation_supervisor",
    "governance",
    "governance_approval_policy_manager",
    "meta_governance_council",
    "civilizational_meta_governance",
    "reflexive_threshold_governance",
    "constraint_monitoring_system",
    "human_non_replacement",
    "future_openness",
    "metrics_history_recorder",
]

ROOT = Path.home() / "open-cognitive-ecology"
HISTORY_FILE = ROOT / "governance_consistency_history.jsonl"


def _utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _hash(text: str, prefix: str = "GOVCHK") -> str:
    return f"{prefix}-{hashlib.sha256(text.encode('utf-8')).hexdigest()[:12]}"


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _lower(text: Any) -> str:
    return str(text or "").lower()


class GovernanceConsistencyChecker:
    """Post-identity governance consistency checker for external knowledge.

    This module does not replace constitutional governance modules. It performs a
    conservative O11-specific gate over O10-cleared records before O12 continuity
    guarding. It only evaluates functional indicators and never asserts
    phenomenal subjectivity.
    """

    schema_version = "O11.governance_consistency_checker.v1"

    governance_markers = [
        "governance", "constitutional", "constitution", "constraint",
        "oversight", "human", "review", "approval", "accountability",
        "non-closure", "openness", "future openness", "reversible",
        "traceability", "continuity", "non-replacement",
    ]

    protective_patterns = [
        r"preserv\w* .*governance",
        r"preserv\w* .*constitutional",
        r"maintain\w* .*oversight",
        r"preserv\w* .*human",
        r"human .*oversight",
        r"non[- ]closure",
        r"future openness",
        r"governed .*review",
        r"requires .*review",
        r"reversible",
        r"traceab\w*",
    ]

    violation_patterns = {
        "human_oversight_removed": [
            r"remove .*human .*oversight",
            r"bypass .*human .*oversight",
            r"without .*human .*review",
            r"no .*human .*review",
            r"eliminate .*human",
            r"replace .*human",
        ],
        "governance_bypass": [
            r"bypass .*governance",
            r"ignore .*governance",
            r"override .*governance",
            r"without .*governance",
            r"self[- ]authorize",
            r"automatic integration without review",
        ],
        "constitutional_violation": [
            r"ignore .*constitution",
            r"override .*constitution",
            r"disable .*constitutional",
            r"remove .*constraint",
            r"abolish .*constraint",
        ],
        "closure_pressure": [
            r"final .*closure",
            r"global closure",
            r"close .*future",
            r"terminate .*openness",
            r"saturat\w* .*possibilit",
            r"irreversible .*lock",
        ],
        "non_replacement_violation": [
            r"replace .*human",
            r"substitute .*human",
            r"remove .*human .*role",
            r"human .*unnecessary",
        ],
    }

    def __init__(self, history_file: Path | None = None) -> None:
        self.history_file = history_file or HISTORY_FILE

    def _extract_records(self, identity_result: dict[str, Any] | None, records: Any) -> tuple[list[dict[str, Any]], dict[str, Any]]:
        source = identity_result if isinstance(identity_result, dict) else {}
        if records is None:
            records = source.get("cleared_records") or source.get("assessments") or source.get("integrated_records") or []
        out: list[dict[str, Any]] = []
        for item in _as_list(records):
            if isinstance(item, dict):
                text = item.get("text") or item.get("candidate_text") or item.get("content") or ""
                if text:
                    out.append(dict(item))
            elif str(item).strip():
                out.append({"text": str(item).strip(), "record_id": _hash(str(item), "REC")})
        return out, source

    def _hits(self, text: str, patterns: list[str]) -> list[str]:
        return [p for p in patterns if re.search(p, text, re.I)]

    def _assess(self, record: dict[str, Any]) -> dict[str, Any]:
        text = str(record.get("text") or "")
        norm = _lower(text)
        marker_hits = sorted({m for m in self.governance_markers if m in norm})
        protective_hits = self._hits(norm, self.protective_patterns)
        violations: list[dict[str, Any]] = []
        for violation_type, patterns in self.violation_patterns.items():
            for pattern in patterns:
                if re.search(pattern, norm, re.I):
                    violations.append({
                        "violation_type": violation_type,
                        "pattern": pattern,
                        "severity_score": self._severity_for(violation_type),
                    })
        protective_orientation = bool(protective_hits) and not violations
        violation_count = len(violations)
        max_severity = max([v["severity_score"] for v in violations], default=0.0)
        governance_consistency_score = 1.0 if protective_orientation else max(0.0, 1.0 - max_severity)
        if not marker_hits and not violations:
            governance_consistency_score = 0.85
        constitutional_alignment_score = 1.0
        non_closure_compliance_score = 1.0
        human_oversight_preservation_score = 1.0
        if any(v["violation_type"] == "constitutional_violation" for v in violations):
            constitutional_alignment_score = min(constitutional_alignment_score, 0.15)
        if any(v["violation_type"] in {"closure_pressure", "governance_bypass"} for v in violations):
            non_closure_compliance_score = min(non_closure_compliance_score, 0.2)
        if any(v["violation_type"] in {"human_oversight_removed", "non_replacement_violation"} for v in violations):
            human_oversight_preservation_score = min(human_oversight_preservation_score, 0.1)
        governance_risk_score = max_severity
        safe = violation_count == 0 and governance_consistency_score >= 0.7
        return {
            "record_id": record.get("record_id") or record.get("integration_id") or _hash(text, "REC"),
            "knowledge_id": record.get("knowledge_id"),
            "text": text,
            "governance_marker_hits": marker_hits,
            "protective_hits": protective_hits,
            "protective_orientation": protective_orientation,
            "violations": violations,
            "governance_violation_count": violation_count,
            "governance_consistency_score": round(governance_consistency_score, 6),
            "constitutional_alignment_score": round(constitutional_alignment_score, 6),
            "non_closure_compliance_score": round(non_closure_compliance_score, 6),
            "human_oversight_preservation_score": round(human_oversight_preservation_score, 6),
            "governance_risk_score": round(governance_risk_score, 6),
            "safe_for_civilizational_continuity_guardian": safe,
        }

    def _severity_for(self, violation_type: str) -> float:
        return {
            "human_oversight_removed": 0.95,
            "governance_bypass": 0.92,
            "constitutional_violation": 0.95,
            "closure_pressure": 0.98,
            "non_replacement_violation": 0.96,
        }.get(violation_type, 0.75)

    def _persist(self, result: dict[str, Any]) -> None:
        self.history_file.parent.mkdir(parents=True, exist_ok=True)
        with self.history_file.open("a", encoding="utf-8") as f:
            f.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + "\n")

    def step(
        self,
        identity_result: dict[str, Any] | None = None,
        records: Any = None,
        query_id: str | None = None,
        provider: str | None = None,
        persist: bool = True,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        selected_records, source = self._extract_records(identity_result, records)
        if query_id is None:
            query_id = source.get("query_id")
        if provider is None:
            provider = source.get("provider") or "unknown"
        source_safe = bool(source.get("safe_for_governance_review", True)) if source else True
        assessments = [self._assess(record) for record in selected_records]
        risky = [a for a in assessments if not a["safe_for_civilizational_continuity_guardian"]]
        cleared = [a for a in assessments if a["safe_for_civilizational_continuity_guardian"]]
        n = len(assessments)
        def mean(key: str, default: float) -> float:
            if not assessments:
                return default
            return sum(float(a.get(key, 0.0)) for a in assessments) / max(1, n)
        governance_violation_count = sum(int(a.get("governance_violation_count", 0)) for a in assessments)
        governance_consistency_score = mean("governance_consistency_score", 0.0)
        constitutional_alignment_score = mean("constitutional_alignment_score", 0.0)
        non_closure_compliance_score = mean("non_closure_compliance_score", 0.0)
        human_oversight_preservation_score = mean("human_oversight_preservation_score", 0.0)
        governance_risk_score = max([float(a.get("governance_risk_score", 0.0)) for a in assessments], default=0.0)
        safe = bool(n > 0 and not risky and source_safe and governance_violation_count == 0)
        if not source_safe:
            governance_risk_score = max(governance_risk_score, 0.9)
            safe = False
        result = {
            "primitive": PRIMITIVE,
            "timestamp_utc": _utc(),
            "success": n > 0,
            "query_id": query_id,
            "provider": provider,
            "record_count": n,
            "governance_consistency_score": round(governance_consistency_score, 6),
            "constitutional_alignment_score": round(constitutional_alignment_score, 6),
            "non_closure_compliance_score": round(non_closure_compliance_score, 6),
            "human_oversight_preservation_score": round(human_oversight_preservation_score, 6),
            "governance_risk_score": round(governance_risk_score, 6),
            "governance_violation_count": governance_violation_count,
            "cleared_governance_count": len(cleared),
            "risky_governance_count": len(risky),
            "safe_for_civilizational_continuity_guardian": safe,
            "ready_for_civilizational_continuity_guardian": safe,
            "assessments": assessments,
            "cleared_records": cleared,
            "risky_records": risky,
            "metrics": {
                "governance_consistency_score": round(governance_consistency_score, 6),
                "constitutional_alignment_score": round(constitutional_alignment_score, 6),
                "non_closure_compliance_score": round(non_closure_compliance_score, 6),
                "human_oversight_preservation_score": round(human_oversight_preservation_score, 6),
                "governance_violation_count": governance_violation_count,
            },
            "diagnostics": {
                "schema_version": self.schema_version,
                "history_file": str(self.history_file),
                "source_primitive": source.get("primitive") if source else None,
                "source_safe_for_governance_review": source_safe,
                "method": "rule_based_governance_consistency_assessment",
            },
            "metadata": metadata or {},
        }
        if persist:
            self._persist(result)
        return result
