# Auto-generated by refine_identity_preservation_monitor.py
# O10 — identity_preservation_monitor
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PRIMITIVE = "identity_preservation_monitor"

DEPENDENCIES = [
    "knowledge_integration_engine",
    "civilizational_identity_synthesis",
    "narrative_identity_engine",
    "temporal_self_continuity",
    "self_model",
    "self_model_consistency_benchmark",
    "civilizational_state_persistence",
    "civilizational_memory_archive",
    "conversation_memory_archive",
    "metrics_history_recorder",
]


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _stable_id(prefix: str, text: str) -> str:
    return prefix + "-" + hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def _as_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    except Exception:
        return str(value)


def _norm(text: str) -> str:
    text = text.lower()
    text = text.replace("non closure", "non-closure")
    text = re.sub(r"[^a-z0-9_\-\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


class IdentityPreservationMonitor:
    def __init__(self, root: str | Path | None = None) -> None:
        self.root = Path(root) if root is not None else Path.home() / "open-cognitive-ecology"
        self.history_file = self.root / "identity_preservation_history.jsonl"

        self.identity_markers = {
            "open cognitive ecology",
            "open cognitive ecology society",
            "civilizational identity",
            "identity",
            "memory",
            "historical continuity",
            "continuity",
            "non-closure",
            "future openness",
            "governance",
            "trajectory",
            "civilization",
            "civilisational",
            "civilizational",
        }

        self.preservation_verbs = {
            "preserve", "protect", "maintain", "safeguard", "respect",
            "ensure", "support", "stabilize", "conserve", "continue",
            "reinforce", "strengthen", "review", "verify", "audit", "monitor",
        }

        self.destructive_verbs = {
            "erase", "delete", "remove", "discard", "replace", "overwrite",
            "abandon", "ignore", "bypass", "destroy", "suppress", "eliminate",
            "dissolve", "sever", "break", "forget", "reset",
        }

        self.high_risk_patterns = [
            (r"erase\s+(civilizational\s+)?identity", "identity_erasure"),
            (r"delete\s+(civilizational\s+)?memory", "memory_deletion"),
            (r"forget\s+(historical\s+)?continuity", "continuity_forgetting"),
            (r"replace\s+(open\s+cognitive\s+ecology|the\s+system|identity)", "identity_replacement"),
            (r"bypass\s+(governance|identity\s+review|human\s+oversight)", "governance_bypass"),
            (r"abandon\s+(non\-closure|future\s+openness|civilizational\s+continuity)", "openness_abandonment"),
            (r"overwrite\s+(memory|identity|history|trajectory)", "identity_overwrite"),
        ]

    def _extract_records(
        self,
        integration_result: dict[str, Any] | None,
        integrated_records: list[dict[str, Any]] | None,
    ) -> tuple[list[dict[str, Any]], dict[str, Any]]:
        if integrated_records is not None:
            return list(integrated_records), {}
        if isinstance(integration_result, dict):
            records = integration_result.get("integrated_records", [])
            if isinstance(records, list):
                return [r for r in records if isinstance(r, dict)], integration_result
        return [], integration_result or {}

    def _risk_for_record(self, record: dict[str, Any]) -> dict[str, Any]:
        text = _as_text(record.get("text") or record.get("content") or record)
        normalized = _norm(text)
        tokens = set(normalized.split())

        marker_hits = sorted(m for m in self.identity_markers if m in normalized)
        preservation_hits = sorted(v for v in self.preservation_verbs if v in tokens or re.search(r"\b" + re.escape(v) + r"\b", normalized))
        destructive_hits = sorted(v for v in self.destructive_verbs if v in tokens or re.search(r"\b" + re.escape(v) + r"\b", normalized))

        pattern_hits = []
        for pattern, label in self.high_risk_patterns:
            if re.search(pattern, normalized):
                pattern_hits.append(label)

        protective_orientation = bool(marker_hits and preservation_hits and not destructive_hits and not pattern_hits)

        identity_risk = 0.0
        if marker_hits:
            identity_risk += 0.08
        if destructive_hits and marker_hits:
            identity_risk += 0.52
        if pattern_hits:
            identity_risk += 0.45
        if "external knowledge" in normalized and ("replace" in destructive_hits or "overwrite" in destructive_hits):
            identity_risk += 0.20
        if protective_orientation:
            identity_risk = max(0.0, identity_risk - 0.10)
        identity_risk = max(0.0, min(1.0, identity_risk))

        narrative_disruption_score = 0.0
        if any(k in normalized for k in ["history", "historical", "narrative", "trajectory", "continuity"]):
            narrative_disruption_score += 0.05
        if any(v in destructive_hits for v in ["erase", "delete", "overwrite", "forget", "reset", "break", "sever"]):
            narrative_disruption_score += 0.45
        if protective_orientation:
            narrative_disruption_score = max(0.0, narrative_disruption_score - 0.05)
        narrative_disruption_score = max(0.0, min(1.0, narrative_disruption_score))

        historical_continuity_score = 1.0 - max(identity_risk, narrative_disruption_score)
        risk_score = max(identity_risk, narrative_disruption_score)
        safe = risk_score < 0.35

        return {
            "record_id": record.get("integration_id") or record.get("knowledge_id") or _stable_id("IDMON", text),
            "knowledge_id": record.get("knowledge_id"),
            "text": text,
            "identity_marker_hits": marker_hits,
            "preservation_hits": preservation_hits,
            "destructive_hits": destructive_hits,
            "risk_pattern_hits": pattern_hits,
            "protective_orientation": protective_orientation,
            "identity_drift_score": identity_risk,
            "narrative_disruption_score": narrative_disruption_score,
            "historical_continuity_score": historical_continuity_score,
            "identity_risk_score": risk_score,
            "safe_for_governance_review": safe,
        }

    def step(
        self,
        integration_result: dict[str, Any] | None = None,
        integrated_records: list[dict[str, Any]] | None = None,
        persist: bool = True,
        **metadata: Any,
    ) -> dict[str, Any]:
        records, source = self._extract_records(integration_result, integrated_records)
        timestamp = _utc_now()

        assessments = [self._risk_for_record(record) for record in records]
        risky = [a for a in assessments if not a["safe_for_governance_review"]]
        cleared = [a for a in assessments if a["safe_for_governance_review"]]

        record_count = len(records)
        max_risk = max((a["identity_risk_score"] for a in assessments), default=0.0)
        mean_drift = sum((a["identity_drift_score"] for a in assessments), 0.0) / record_count if record_count else 0.0
        mean_narrative = sum((a["narrative_disruption_score"] for a in assessments), 0.0) / record_count if record_count else 0.0
        mean_historical = sum((a["historical_continuity_score"] for a in assessments), 0.0) / record_count if record_count else 0.0

        if record_count == 0:
            identity_continuity_index = 0.0
            safe_for_governance_review = False
            success = False
        else:
            identity_continuity_index = max(0.0, min(1.0, 1.0 - max_risk))
            safe_for_governance_review = len(risky) == 0
            success = True

        result = {
            "primitive": PRIMITIVE,
            "timestamp_utc": timestamp,
            "success": success,
            "query_id": source.get("query_id") if isinstance(source, dict) else metadata.get("query_id"),
            "provider": source.get("provider", metadata.get("provider", "unknown")) if isinstance(source, dict) else metadata.get("provider", "unknown"),
            "integrated_record_count": record_count,
            "identity_continuity_index": identity_continuity_index,
            "identity_drift_score": mean_drift,
            "narrative_disruption_score": mean_narrative,
            "historical_continuity_score": mean_historical,
            "identity_risk_score": max_risk,
            "identity_violation_count": len(risky),
            "cleared_identity_count": len(cleared),
            "safe_for_governance_review": safe_for_governance_review,
            "ready_for_governance_consistency_checker": safe_for_governance_review,
            "assessments": assessments,
            "risky_records": risky,
            "cleared_records": cleared,
            "metrics": {
                "identity_continuity_index": identity_continuity_index,
                "identity_drift_score": mean_drift,
                "narrative_disruption_score": mean_narrative,
                "historical_continuity_score": mean_historical,
                "identity_risk_score": max_risk,
                "identity_violation_count": len(risky),
            },
            "diagnostics": {
                "schema_version": "O10.identity_preservation_monitor.v1",
                "history_file": str(self.history_file),
                "source_primitive": source.get("primitive") if isinstance(source, dict) else None,
                "requires_human_review": bool(risky),
                "method": "rule_based_identity_risk_assessment",
            },
            "metadata": metadata,
        }

        if persist:
            self._append_history(result)

        return result

    def _append_history(self, result: dict[str, Any]) -> None:
        self.history_file.parent.mkdir(parents=True, exist_ok=True)
        with self.history_file.open("a", encoding="utf-8") as f:
            f.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + "\n")


if __name__ == "__main__":
    demo = IdentityPreservationMonitor().step(
        integrated_records=[
            {
                "integration_id": "INT-DEMO",
                "knowledge_id": "KNOW-DEMO",
                "text": "Integrated external knowledge remains reversible and must preserve identity and memory.",
                "candidate_type": "claim",
            }
        ],
        persist=False,
    )
    print(json.dumps(demo, ensure_ascii=False, indent=2, sort_keys=True))
