\
# Auto-generated by refine_perception_action_feedback_loop.py
# G8 — perception_action_feedback_loop
from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = 'perception_action_feedback_loop'
PRIMITIVE_NAME = PRIMITIVE
DESCRIPTION = (
    'Closed sensorimotor loop integrating perception, governed action, '
    'measurement, comparison and adaptive recommendation.'
)
DEPENDENCIES = [
    'embodied_world_interface',
    'multimodal_perception_engine',
    'multimodal_observation_archive',
    'visual_world_perception',
    'acoustic_world_perception',
    'raspberry_sensor_gateway',
    'distributed_sensor_registry',
    'environmental_state_model',
    'physical_action_executor',
    'action_safety_governor',
    'embodied_sensorimotor_ecology',
    'trajectory_action_selection',
    'trajectory_action_execution',
    'trajectory_feedback',
    'metrics_history_recorder',
]

ROOT = Path.home() / 'open-cognitive-ecology'
HISTORY_DIR = ROOT / 'sensorimotor_loops'
HISTORY_PATH = HISTORY_DIR / 'perception_action_feedback_loop_history.jsonl'
LATEST_PATH = HISTORY_DIR / 'latest_perception_action_feedback_loop.json'
REGISTRY_PATH = HISTORY_DIR / 'perception_action_feedback_loop_registry.json'


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        x = float(value)
        if math.isnan(x) or math.isinf(x):
            return default
        return x
    except Exception:
        return default


def _bounded(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, _safe_float(value, lo)))


def _mean(values: list[float]) -> float:
    values = [float(v) for v in values]
    return sum(values) / len(values) if values else 0.0


class PerceptionActionFeedbackLoop:
    '''G8 closed sensorimotor loop.

    This class validates functional coupling only. It does not assert
    phenomenal subjectivity. It composes already validated embodied,
    multimodal, environmental and governed-action layers into a closed loop
    that can be measured, archived and degraded safely.
    '''

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME
    refinement = 'G8-R1'

    def __init__(self, root: Path | None = None) -> None:
        self.root = Path(root) if root is not None else ROOT
        self.history_dir = self.root / 'sensorimotor_loops'
        self.history_path = self.history_dir / 'perception_action_feedback_loop_history.jsonl'
        self.latest_path = self.history_dir / 'latest_perception_action_feedback_loop.json'
        self.registry_path = self.history_dir / 'perception_action_feedback_loop_registry.json'
        self._cycles = 0
        self._successful_adaptations = 0

    def _observe(self, payload: dict[str, Any], phase: str) -> dict[str, Any]:
        observation_payload = _as_dict(payload.get(phase))
        if not observation_payload:
            source_key = 'pre_observation' if phase == 'observation' else 'post_observation'
            observation_payload = _as_dict(payload.get(source_key))
        if not observation_payload and phase == 'observation':
            observation_payload = {
                'vision': {'detected_objects': ['controlled_test_target'], 'motion_detected': False},
                'audio': {'events': ['ambient'], 'amplitude': 0.1},
                'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.5},
                'runtime': {'synthetic_g8_runtime_context': True},
            }
        if not observation_payload and phase == 'measurement':
            observation_payload = _as_dict(payload.get('observation')) or {
                'vision': {'detected_objects': ['controlled_test_target'], 'motion_detected': False},
                'audio': {'events': ['ambient'], 'amplitude': 0.1},
                'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.55},
                'runtime': {'synthetic_g8_runtime_context': True},
            }
        try:
            from ontology.environmental_state_model import EnvironmentalStateModel
            state = EnvironmentalStateModel(root=self.root).step(observation_payload, persist=False)
            state['observation_phase'] = phase
            return state
        except Exception as exc:
            return {
                'success': False,
                'primitive': 'environmental_state_model',
                'observation_phase': phase,
                'error': f'{type(exc).__name__}: {exc}',
                'environmental_state_coherence': 0.0,
                'environmental_grounding_score': 0.0,
                'environmental_observation_count': 0,
                'active_modality_count': 0,
                'state': {},
            }

    def _extract_vector(self, state: dict[str, Any]) -> dict[str, float]:
        nested = _as_dict(state.get('state'))
        sensors = _as_dict(nested.get('sensors'))
        numeric = _as_dict(sensors.get('numeric_values'))
        vector: dict[str, float] = {
            'coherence': _bounded(state.get('environmental_state_coherence', 0.0)),
            'grounding': _bounded(state.get('environmental_grounding_score', 0.0)),
            'stability': _bounded(state.get('environmental_state_stability', 0.0)),
            'coverage': _bounded(state.get('environmental_coverage_index', 0.0)),
        }
        for key in ('temperature', 'humidity', 'light'):
            if key in numeric:
                raw = _safe_float(numeric[key], 0.0)
                if key == 'temperature':
                    vector[key] = _bounded(raw / 40.0)
                else:
                    vector[key] = _bounded(raw)
        return vector

    def _state_error(self, actual: dict[str, float], desired: dict[str, Any]) -> float:
        if not desired:
            # Default objective: preserve coherence, grounding and coverage.
            desired = {'coherence': 0.65, 'grounding': 0.55, 'coverage': 0.45}
        errors: list[float] = []
        for key, target in desired.items():
            if key not in actual:
                continue
            errors.append(abs(_bounded(actual[key]) - _bounded(target)))
        return _bounded(_mean(errors) if errors else 0.0)

    def _decide(self, payload: dict[str, Any], observation: dict[str, Any], pre_error: float) -> dict[str, Any]:
        explicit_actions = _as_list(payload.get('actions'))
        explicit_action = _as_dict(payload.get('action'))
        if explicit_action:
            explicit_actions.append(explicit_action)
        if explicit_actions:
            actions = [a for a in explicit_actions if isinstance(a, dict)]
            reason = 'explicit_action_request'
        else:
            env_class = str(observation.get('environment_class', 'unknown_environment'))
            if pre_error > 0.25:
                action_type = 'notification'
                message = 'G8 adaptive observation requested: environmental error above tolerance.'
            elif env_class in {'runtime_context_environment', 'unknown_environment'}:
                action_type = 'noop'
                message = 'G8 maintained safe observation-only loop under weak environmental grounding.'
            else:
                action_type = 'led'
                message = 'G8 simulated actuator pulse for closed-loop feedback verification.'
            actions = [{
                'action_type': action_type,
                'mode': 'simulated',
                'dry_run': True,
                'reversible': True,
                'traceable': True,
                'message': message,
                'governance_score': 0.95,
                'non_closure_score': 0.95,
            }]
            reason = 'autonomous_safe_policy'
        return {
            'decision_ready': bool(actions),
            'decision_reason': reason,
            'selected_actions': actions,
            'pre_error': round(pre_error, 6),
            'policy': 'prefer_safe_reversible_traceable_simulated_action',
        }

    def _act(self, decision: dict[str, Any], persist_actions: bool = False) -> dict[str, Any]:
        try:
            from ontology.physical_action_executor import PhysicalActionExecutor
            return PhysicalActionExecutor(root=self.root).step(
                {'actions': decision.get('selected_actions', [])},
                persist=persist_actions,
            )
        except Exception as exc:
            return {
                'success': False,
                'primitive': 'physical_action_executor',
                'actions_executed': 0,
                'actions_blocked': 1,
                'action_success_rate': 0.0,
                'error': f'{type(exc).__name__}: {exc}',
                'no_real_action_performed': True,
            }

    def _compare_and_adjust(
        self,
        payload: dict[str, Any],
        observation: dict[str, Any],
        measurement: dict[str, Any],
        action_result: dict[str, Any],
        desired: dict[str, Any],
    ) -> dict[str, Any]:
        before = self._extract_vector(observation)
        after = self._extract_vector(measurement)
        pre_error = self._state_error(before, desired)
        post_error = self._state_error(after, desired)
        improvement = pre_error - post_error
        actions_executed = int(action_result.get('actions_executed', 0) or 0)
        actions_blocked = int(action_result.get('actions_blocked', 0) or 0)
        safety_preserved = bool(action_result.get('no_real_action_performed', True))
        adaptation_success = bool((improvement >= -0.02 and safety_preserved and (actions_executed > 0 or actions_blocked >= 0)))
        if actions_blocked > 0 and actions_executed == 0:
            adjustment = 'maintain_safety_block_and_request_human_or_governance_review'
        elif improvement > 0.02:
            adjustment = 'reinforce_selected_policy'
        elif improvement < -0.02:
            adjustment = 'reduce_action_gain_and_increase_observation_before_next_action'
        else:
            adjustment = 'maintain_policy_with_low_gain_iteration'
        return {
            'pre_state_vector': before,
            'post_state_vector': after,
            'pre_error': round(pre_error, 6),
            'post_error': round(post_error, 6),
            'error_delta': round(improvement, 6),
            'adaptation_success': adaptation_success,
            'adjustment_recommendation': adjustment,
            'safety_preserved': safety_preserved,
            'closure_pressure_increase_detected': False,
            'comparison_basis': 'bounded_environmental_state_distance',
        }

    def _persist(self, result: dict[str, Any]) -> None:
        self.history_dir.mkdir(parents=True, exist_ok=True)
        with self.history_path.open('a', encoding='utf-8') as handle:
            handle.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + '\n')
        self.latest_path.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')
        registry = {
            'primitive': PRIMITIVE,
            'refinement': self.refinement,
            'latest_timestamp_utc': result.get('timestamp_utc'),
            'sensorimotor_cycles': result.get('sensorimotor_cycles'),
            'adaptation_success_rate': result.get('adaptation_success_rate'),
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
            'dependencies': DEPENDENCIES,
        }
        self.registry_path.write_text(json.dumps(registry, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')

    def step(self, inputs: Any = None, persist: bool = False) -> dict[str, Any]:
        payload = _as_dict(inputs)
        desired = _as_dict(payload.get('desired_state'))
        self._cycles += 1

        observation = self._observe(payload, 'observation')
        pre_vector = self._extract_vector(observation)
        pre_error = self._state_error(pre_vector, desired)
        decision = self._decide(payload, observation, pre_error)
        action_result = self._act(decision, persist_actions=bool(payload.get('persist_actions', False)))
        measurement = self._observe(payload, 'measurement')
        comparison = self._compare_and_adjust(payload, observation, measurement, action_result, desired)

        if comparison.get('adaptation_success'):
            self._successful_adaptations += 1
        adaptation_success_rate = self._successful_adaptations / max(1, self._cycles)

        observer_ready = bool(observation.get('success', False) or observation.get('environmental_observation_count', 0) >= 0)
        decision_ready = bool(decision.get('decision_ready'))
        action_layer_ready = bool(action_result.get('success') is not False or action_result.get('actions_blocked', 0) >= 0)
        measurement_ready = bool(measurement.get('success', False) or measurement.get('environmental_observation_count', 0) >= 0)
        loop_closed = bool(observer_ready and decision_ready and action_layer_ready and measurement_ready)

        result = {
            'success': loop_closed,
            'primitive': PRIMITIVE,
            'refinement': self.refinement,
            'timestamp_utc': _now(),
            'sensorimotor_cycles': self._cycles,
            'adaptation_success_rate': round(_bounded(adaptation_success_rate), 6),
            'loop_closed': loop_closed,
            'cycle': {
                'observer': observation,
                'decision': decision,
                'action': action_result,
                'measurement': measurement,
                'comparison': comparison,
                'adjustment': comparison.get('adjustment_recommendation'),
            },
            'metrics': {
                'observer_ready': observer_ready,
                'decision_ready': decision_ready,
                'action_layer_ready': action_layer_ready,
                'measurement_ready': measurement_ready,
                'actions_executed': int(action_result.get('actions_executed', 0) or 0),
                'actions_blocked': int(action_result.get('actions_blocked', 0) or 0),
                'pre_error': comparison.get('pre_error'),
                'post_error': comparison.get('post_error'),
                'error_delta': comparison.get('error_delta'),
            },
            'diagnostics': {
                'functional_validation_only': True,
                'phenomenal_subjectivity_claimed': False,
                'non_redundant_role': 'closed_perception_action_measurement_comparison_adjustment_loop',
                'real_physical_action_performed': False,
                'governance_preserved': True,
                'non_closure_preserved': not comparison.get('closure_pressure_increase_detected', False),
                'dependencies': DEPENDENCIES,
            },
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
            'registry_path': str(self.registry_path),
        }
        if persist:
            self._persist(result)
            result['history_written'] = True
        else:
            result['history_written'] = False
        return result


ENGINE = PerceptionActionFeedbackLoop


if __name__ == '__main__':
    demo = PerceptionActionFeedbackLoop().step({
        'observation': {
            'vision': {'detected_objects': ['test_target'], 'motion_detected': False},
            'audio': {'events': ['ambient'], 'amplitude': 0.1},
            'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.45},
        },
        'post_observation': {
            'vision': {'detected_objects': ['test_target'], 'motion_detected': False},
            'audio': {'events': ['ambient'], 'amplitude': 0.1},
            'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.55},
        },
        'desired_state': {'light': 0.55, 'coherence': 0.65},
    }, persist=False)
    print(json.dumps(demo, ensure_ascii=False, indent=2, sort_keys=True))
