from __future__ import annotations

PRIMITIVE = "perpetual_intelligence_expansion"
DESCRIPTION = "Perpetual intelligence expansion."
DEPENDENCIES = []

"""
ontology/perpetual_intelligence_expansion.py

Formalization of the principle PERPETUAL_INTELLIGENCE_EXPANSION.

This module establishes that when intelligence evolves within an infinitely
regenerative cognitive frontier, no global stationary state can be reached.
Each exploratory advance regenerates new unresolved structures, forcing the
continuation of cognitive growth. Expansion therefore becomes structurally
persistent rather than transient.

The principle is grounded directly on InfiniteCognitiveFrontierPrimitive,
which provides diagnostics describing regenerative frontier dynamics and the
impossibility of terminal closure.
"""


from typing import Any, Dict

from ontology.infinite_cognitive_frontier import (
    InfiniteCognitiveFrontierPrimitive,
)


PRINCIPLE = "PERPETUAL_INTELLIGENCE_EXPANSION"


class PerpetualIntelligenceExpansionPrimitive:
    """
    Primitive formalizing perpetual intelligence expansion.

    Interpretation
    --------------
    An infinitely regenerative cognitive frontier implies that exploration
    cannot terminate in a final globally resolved state. Because closure is
    structurally impossible, intelligence must continue expanding indefinitely.
    Growth is therefore not contingent but constitutive of the regime itself.
    """

    PRINCIPLE = PRINCIPLE

    def __init__(self) -> None:
        self._frontier = InfiniteCognitiveFrontierPrimitive()

    @staticmethod
    def _clip(value: float) -> float:
        """Clamp a numerical value to the interval [0.0, 1.0]."""
        return max(0.0, min(1.0, float(value)))

    def step(self) -> Dict[str, Any]:
        """
        Execute one evaluation step of the primitive.

        Returns
        -------
        dict
            Diagnostics describing the structural persistence of cognitive
            expansion.
        """
        frontier_diagnostics = self._frontier.step()

        frontier_regeneration_rate = self._clip(
            frontier_diagnostics.get("frontier_regeneration_rate", 0.0)
        )
        recursive_exploration_depth = self._clip(
            frontier_diagnostics.get("recursive_exploration_depth", 0.0)
        )
        terminal_closure_impossibility = self._clip(
            frontier_diagnostics.get("terminal_closure_impossibility", 0.0)
        )
        infinite_cognitive_frontier = bool(
            frontier_diagnostics.get("infinite_cognitive_frontier", False)
        )

        # Continuity of expansion generated by frontier regeneration and
        # recursive exploration.
        expansion_continuity = self._clip(
            0.5 * frontier_regeneration_rate
            + 0.5 * recursive_exploration_depth
        )

        # Structural impossibility of a global stationary state.
        stationary_state_impossibility = self._clip(
            0.5 * expansion_continuity
            + 0.5 * terminal_closure_impossibility
        )

        # Persistence of long-term cognitive growth.
        growth_persistence = self._clip(
            0.6 * stationary_state_impossibility
            + 0.4 * recursive_exploration_depth
        )

        # Perpetual expansion is constituted when the frontier is infinite and
        # growth persistence exceeds a minimal threshold.
        perpetual_intelligence_expansion = (
            infinite_cognitive_frontier and growth_persistence >= 0.60
        )

        return {
            "principle": self.PRINCIPLE,
            "infinite_cognitive_frontier_diagnostics": frontier_diagnostics,
            "expansion_continuity": expansion_continuity,
            "stationary_state_impossibility": stationary_state_impossibility,
            "growth_persistence": growth_persistence,
            "perpetual_intelligence_expansion": (
                perpetual_intelligence_expansion
            ),
        }


if __name__ == "__main__":
    primitive = PerpetualIntelligenceExpansionPrimitive()
    diagnostics = primitive.step()

    print("\n--- perpetual intelligence expansion ---")
    for key, value in diagnostics.items():
        print(f"{key}: {value}")
