# Auto-generated by refine_physical_environment_alert_router.py
# G10 — physical_environment_alert_router
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = 'physical_environment_alert_router'
PRIMITIVE_NAME = PRIMITIVE
DESCRIPTION = (
    'Routes real-world physical/environmental events toward notification, '
    'memory, governance, metrics and longitudinal archives without adding '
    'any real physical action surface.'
)
DEPENDENCIES = [
    'real_world_event_detection',
    'perception_action_feedback_loop',
    'environmental_state_model',
    'alerting_and_notification_system',
    'constitutional_alert_system',
    'constitutional_governance_supervisor',
    'civilizational_memory_archive',
    'conversation_memory_archive',
    'metrics_history_recorder',
    'scientific_anomaly_detector',
    'constraint_monitoring_system',
    'openness_preservation_supervisor',
    'non_closure_certification_protocol',
    'action_safety_governor',
]

ROOT = Path.home() / 'open-cognitive-ecology'
ALERT_DIR = ROOT / 'physical_environment_alerts'
HISTORY_PATH = ALERT_DIR / 'physical_environment_alert_router_history.jsonl'
LATEST_PATH = ALERT_DIR / 'latest_physical_environment_alert_router.json'
ROUTE_INDEX_PATH = ALERT_DIR / 'physical_environment_alert_route_index.json'


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, set):
        return list(value)
    return [value]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _bounded(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, _safe_float(value, lo)))


def _severity_class(score: float) -> str:
    if score >= 0.75:
        return 'critical'
    if score >= 0.50:
        return 'high'
    if score >= 0.25:
        return 'medium'
    if score > 0.0:
        return 'low'
    return 'none'


def _event_severity(event: dict[str, Any], fallback: float = 0.0) -> float:
    return _bounded(event.get('severity', fallback))


def _event_channel(event: dict[str, Any]) -> str:
    channel = event.get('channel') or event.get('event_channel') or 'unknown'
    return str(channel)


def _event_type(event: dict[str, Any]) -> str:
    event_type = event.get('event_type') or event.get('type') or 'unknown_event'
    return str(event_type)


def _load_json(path: Path, default: Any) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding='utf-8'))
    except Exception:
        pass
    return default


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')


def _append_jsonl(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + '\n')


class PhysicalEnvironmentAlertRouter:
    """Routeur G10 pour événements environnementaux physiques détectés par G9."""

    def __init__(
        self,
        notification_threshold: float = 0.30,
        governance_threshold: float = 0.65,
        memory_threshold: float = 0.01,
    ) -> None:
        self.notification_threshold = _bounded(notification_threshold)
        self.governance_threshold = _bounded(governance_threshold)
        self.memory_threshold = _bounded(memory_threshold)
        self._cycle_counter = 0

    def _normalise_inputs(self, inputs: Any) -> dict[str, Any]:
        data = _as_dict(inputs)
        if not data:
            latest = _load_json(ROOT / 'real_world_events' / 'latest_real_world_event_detection.json', {})
            data = _as_dict(latest)
        detection = _as_dict(data.get('event_detection_result')) or data
        events = [_as_dict(event) for event in _as_list(detection.get('events')) if isinstance(event, dict)]
        return {
            'raw_inputs': data,
            'detection': detection,
            'events': events,
        }

    def _route_event(self, event: dict[str, Any], default_severity: float) -> dict[str, Any]:
        severity = _event_severity(event, default_severity)
        channel = _event_channel(event)
        event_type = _event_type(event)
        severity_label = _severity_class(severity)

        routes: list[str] = []
        reasons: list[str] = []

        if severity >= self.memory_threshold:
            routes.append('memory')
            reasons.append('event_trace_preservation')

        if severity >= self.notification_threshold:
            routes.append('notification')
            reasons.append('operator_awareness_threshold_reached')

        if severity >= self.governance_threshold:
            routes.append('governance')
            reasons.append('high_severity_governance_review_required')

        if channel == 'runtime':
            if 'notification' not in routes:
                routes.append('notification')
            if 'governance' not in routes:
                routes.append('governance')
            reasons.append('runtime_infrastructure_event')

        if event_type in {'storage_state_changed', 'network_state_changed', 'device_state_changed'}:
            if 'governance' not in routes:
                routes.append('governance')
            reasons.append('infrastructure_continuity_signal')

        if not routes:
            routes.append('metrics')
            reasons.append('low_severity_metric_only')
        elif 'metrics' not in routes:
            routes.append('metrics')

        return {
            'event_type': event_type,
            'channel': channel,
            'severity': round(severity, 6),
            'severity_class': severity_label,
            'routes': routes,
            'route_count': len(routes),
            'route_reasons': sorted(set(reasons)),
            'event': event,
        }

    def _aggregate_routes(self, routed_events: list[dict[str, Any]]) -> dict[str, Any]:
        route_counts = {
            'notification': 0,
            'memory': 0,
            'governance': 0,
            'metrics': 0,
        }
        for routed in routed_events:
            for route in routed.get('routes', []):
                route_counts[route] = route_counts.get(route, 0) + 1

        total = len(routed_events)
        routed_total = sum(1 for item in routed_events if item.get('routes'))
        max_severity = max([_safe_float(item.get('severity')) for item in routed_events], default=0.0)
        mean_routes = (
            sum(int(item.get('route_count', 0)) for item in routed_events) / total
            if total else 0.0
        )
        route_success_rate = routed_total / total if total else 1.0
        governance_pressure = min(1.0, route_counts.get('governance', 0) / max(1, total))
        notification_pressure = min(1.0, route_counts.get('notification', 0) / max(1, total))

        return {
            'route_counts': route_counts,
            'route_success_rate': round(route_success_rate, 6),
            'max_routed_event_severity': round(max_severity, 6),
            'mean_routes_per_event': round(mean_routes, 6),
            'governance_routing_pressure': round(governance_pressure, 6),
            'notification_routing_pressure': round(notification_pressure, 6),
        }

    def step(self, inputs: Any = None, persist: bool = True) -> dict[str, Any]:
        self._cycle_counter += 1
        normalised = self._normalise_inputs(inputs)
        detection = normalised['detection']
        events = normalised['events']
        default_severity = _bounded(detection.get('event_severity_index', 0.0))

        routed_events = [self._route_event(event, default_severity) for event in events]
        aggregate = self._aggregate_routes(routed_events)
        route_counts = aggregate['route_counts']

        alert_generated = bool(
            route_counts.get('notification', 0)
            or route_counts.get('governance', 0)
        )
        governance_escalation_required = bool(route_counts.get('governance', 0))
        memory_archival_required = bool(route_counts.get('memory', 0))

        result = {
            'success': True,
            'primitive': PRIMITIVE,
            'refinement': 'G10-R1',
            'timestamp_utc': _now(),
            'alert_router_cycles': self._cycle_counter,
            'source_primitive': detection.get('primitive', 'real_world_event_detection'),
            'source_detected_events': int(detection.get('detected_events', len(events)) or 0),
            'routed_events': routed_events,
            'routed_event_count': len(routed_events),
            'alert_generated': alert_generated,
            'notification_count': route_counts.get('notification', 0),
            'memory_record_count': route_counts.get('memory', 0),
            'governance_escalation_count': route_counts.get('governance', 0),
            'metrics_route_count': route_counts.get('metrics', 0),
            'governance_escalation_required': governance_escalation_required,
            'memory_archival_required': memory_archival_required,
            'route_success_rate': aggregate['route_success_rate'],
            'max_routed_event_severity': aggregate['max_routed_event_severity'],
            'mean_routes_per_event': aggregate['mean_routes_per_event'],
            'route_counts': route_counts,
            'recommended_actions': self._recommended_actions(route_counts, aggregate),
            'history_path': str(HISTORY_PATH),
            'latest_path': str(LATEST_PATH),
            'metrics': {
                'physical_environment_alerts_generated': 1 if alert_generated else 0,
                'routed_event_count': len(routed_events),
                'notification_count': route_counts.get('notification', 0),
                'memory_record_count': route_counts.get('memory', 0),
                'governance_escalation_count': route_counts.get('governance', 0),
                'route_success_rate': aggregate['route_success_rate'],
                'max_routed_event_severity': aggregate['max_routed_event_severity'],
                'governance_routing_pressure': aggregate['governance_routing_pressure'],
                'notification_routing_pressure': aggregate['notification_routing_pressure'],
            },
            'diagnostics': {
                'functional_validation_only': True,
                'phenomenal_subjectivity_claimed': False,
                'non_redundant_role': 'route_physical_environment_events_to_alert_memory_governance_metrics',
                'real_physical_action_performed': False,
                'dangerous_action_surface_added': False,
                'governance_preserved': True,
                'non_closure_preserved': True,
                'routes_supported': ['notification', 'memory', 'governance', 'metrics'],
                'dependencies': list(DEPENDENCIES),
            },
            'persisted': bool(persist),
        }

        if persist:
            self._persist(result)

        return result

    def _recommended_actions(self, route_counts: dict[str, int], aggregate: dict[str, Any]) -> list[str]:
        actions: list[str] = []
        if route_counts.get('governance', 0):
            actions.append('review_high_severity_environmental_or_runtime_event')
        if route_counts.get('notification', 0):
            actions.append('notify_operator_or_civilizational_agent')
        if route_counts.get('memory', 0):
            actions.append('archive_event_for_longitudinal_environmental_memory')
        if aggregate.get('max_routed_event_severity', 0.0) >= 0.75:
            actions.append('increase_monitoring_frequency_temporarily')
        if not actions:
            actions.append('continue_passive_environmental_monitoring')
        return actions

    def _persist(self, result: dict[str, Any]) -> None:
        ALERT_DIR.mkdir(parents=True, exist_ok=True)
        _append_jsonl(HISTORY_PATH, result)
        _write_json(LATEST_PATH, result)

        index = _load_json(ROUTE_INDEX_PATH, {
            'primitive': PRIMITIVE,
            'total_cycles': 0,
            'total_routed_events': 0,
            'total_notifications': 0,
            'total_memory_records': 0,
            'total_governance_escalations': 0,
        })
        index['total_cycles'] = int(index.get('total_cycles', 0)) + 1
        index['total_routed_events'] = int(index.get('total_routed_events', 0)) + int(result.get('routed_event_count', 0))
        index['total_notifications'] = int(index.get('total_notifications', 0)) + int(result.get('notification_count', 0))
        index['total_memory_records'] = int(index.get('total_memory_records', 0)) + int(result.get('memory_record_count', 0))
        index['total_governance_escalations'] = int(index.get('total_governance_escalations', 0)) + int(result.get('governance_escalation_count', 0))
        index['latest_timestamp_utc'] = result.get('timestamp_utc')
        index['latest_path'] = str(LATEST_PATH)
        _write_json(ROUTE_INDEX_PATH, index)


class PhysicalEnvironmentalAlertRouter(PhysicalEnvironmentAlertRouter):
    """Alias tolérant pour graphes ou imports utilisant environmental."""


__all__ = [
    'PhysicalEnvironmentAlertRouter',
    'PhysicalEnvironmentalAlertRouter',
    'PRIMITIVE',
    'DEPENDENCIES',
]
