# Auto-generated by refine_physical_action_executor_fix2.py
# G7 — physical_action_executor
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = "physical_action_executor"
PRIMITIVE_NAME = "physical_action_executor"
DESCRIPTION = "Execute governed physical or system actions in simulated-safe mode by default."
DEPENDENCIES = [
    "action_safety_governor",
    "environmental_state_model",
    "raspberry_sensor_gateway",
    "distributed_sensor_registry",
    "trajectory_action_selection",
    "governance_consistency_checker",
    "metrics_history_recorder",
]

ROOT = Path.home() / "open-cognitive-ecology"
HISTORY_DIR = ROOT / "physical_actions"
HISTORY_PATH = HISTORY_DIR / "physical_action_executor_history.jsonl"
LATEST_PATH = HISTORY_DIR / "latest_physical_action_executor.json"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _clip(x: Any, default: float = 0.0) -> float:
    try:
        v = float(x)
    except Exception:
        v = default
    return max(0.0, min(1.0, v))


def _as_dict(inputs: Any) -> dict[str, Any]:
    return inputs if isinstance(inputs, dict) else {}


class PhysicalActionExecutor:
    '''Governed executor for physical/system action requests.

    The executor is intentionally conservative: simulated actions can be
    recorded as executed; real GPIO/relay/service actions are never performed
    by default. A future hardware backend may be attached only behind explicit
    authorization, dry-run and reversibility gates.
    '''

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME

    def __init__(self, root: Path | None = None):
        self.root = Path(root) if root else ROOT
        self.history_dir = self.root / "physical_actions"
        self.history_path = self.history_dir / "physical_action_executor_history.jsonl"
        self.latest_path = self.history_dir / "latest_physical_action_executor.json"

    def _govern(self, data: dict[str, Any]) -> dict[str, Any]:
        try:
            from ontology.action_safety_governor import ActionSafetyGovernor
            return ActionSafetyGovernor(root=self.root).step(data, persist=False)
        except Exception as exc:
            return {
                "success": False,
                "actions_authorized": 0,
                "actions_blocked": 1,
                "blocked_reasons": [f"governor_unavailable:{type(exc).__name__}"],
                "evaluations": [],
            }

    def _execute_authorized(self, evaluation: dict[str, Any]) -> dict[str, Any]:
        action = evaluation.get("action", {}) if isinstance(evaluation.get("action"), dict) else {}
        action_type = evaluation.get("action_type", "noop")
        mode = evaluation.get("mode", "simulated")

        # Only simulated/dry-run execution is implemented. This is deliberate.
        if mode == "real":
            return {
                "executed": False,
                "execution_mode": "blocked_real_backend_unavailable",
                "action_type": action_type,
                "success": False,
                "effect": None,
            }

        if action_type == "file":
            # Simulate file action unless explicitly safe_write=True.
            if action.get("safe_write") is True:
                safe_dir = self.root / "physical_actions" / "safe_file_actions"
                safe_dir.mkdir(parents=True, exist_ok=True)
                target = safe_dir / str(action.get("filename", "simulated_action.txt"))
                target.write_text(str(action.get("content", "simulated physical action")), encoding="utf-8")
                effect = str(target)
            else:
                effect = "simulated_file_action"
        elif action_type == "led":
            effect = "simulated_led_signal"
        elif action_type == "message" or action_type == "notification":
            effect = "simulated_message_emission"
        elif action_type == "gpio":
            effect = "simulated_gpio_signal"
        elif action_type == "relay":
            effect = "simulated_relay_signal"
        elif action_type == "service":
            effect = "simulated_service_action"
        else:
            effect = "simulated_noop"

        return {
            "executed": True,
            "execution_mode": "simulated",
            "action_type": action_type,
            "success": True,
            "effect": effect,
        }

    def _persist(self, result: dict[str, Any]) -> None:
        self.history_dir.mkdir(parents=True, exist_ok=True)
        with self.history_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + "\n")
        self.latest_path.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")

    def step(self, inputs: Any = None, persist: bool = False) -> dict[str, Any]:
        data = _as_dict(inputs)
        governance = self._govern(data)
        evaluations = governance.get("evaluations") or governance.get("authorized_actions") or []
        authorized = [e for e in evaluations if isinstance(e, dict) and e.get("authorized")]
        blocked_count = int(governance.get("actions_blocked", 0) or 0)
        executions = [self._execute_authorized(e) for e in authorized]
        successful = [e for e in executions if e.get("executed") and e.get("success")]

        actions_executed = len(successful)
        actions_reviewed = int(governance.get("actions_reviewed", len(evaluations)) or len(evaluations))
        action_success_rate = actions_executed / max(1, actions_executed + blocked_count)
        success = bool(governance.get("success") is True and (actions_executed > 0 or blocked_count > 0))

        result = {
            "success": success,
            "primitive": PRIMITIVE,
            "timestamp_utc": _now(),
            "actions_reviewed": actions_reviewed,
            "actions_executed": actions_executed,
            "actions_blocked": blocked_count,
            "action_success_rate": round(_clip(action_success_rate), 6),
            "execution_results": executions,
            "governance": governance,
            "no_real_action_performed": True,
            "real_action_backend_enabled": False,
            "history_path": str(self.history_path),
            "latest_path": str(self.latest_path),
        }
        if persist:
            self._persist(result)
        return result


ENGINE = PhysicalActionExecutor

if __name__ == "__main__":
    print(json.dumps(PhysicalActionExecutor().step({"action": {"action_type": "led", "mode": "simulated"}}, persist=False), indent=2))
