# Auto-generated by refine_real_world_event_detection.py
# G9 — real_world_event_detection
from __future__ import annotations

import json
import math
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRIMITIVE = 'real_world_event_detection'
PRIMITIVE_NAME = PRIMITIVE
DESCRIPTION = (
    'Real-world event detection layer comparing successive multimodal and '
    'environmental observations, classifying changes, scoring severity and '
    'persisting traceable event records.'
)
DEPENDENCIES = [
    'embodied_world_interface',
    'multimodal_perception_engine',
    'multimodal_observation_archive',
    'visual_world_perception',
    'acoustic_world_perception',
    'raspberry_sensor_gateway',
    'distributed_sensor_registry',
    'environmental_state_model',
    'perception_action_feedback_loop',
    'scientific_anomaly_detector',
    'constraint_monitoring_system',
    'civilizational_memory_archive',
    'metrics_history_recorder',
    'alerting_and_notification_system',
]

ROOT = Path.home() / 'open-cognitive-ecology'
EVENT_DIR = ROOT / 'real_world_events'
HISTORY_PATH = EVENT_DIR / 'real_world_event_detection_history.jsonl'
LATEST_PATH = EVENT_DIR / 'latest_real_world_event_detection.json'
EVENT_INDEX_PATH = EVENT_DIR / 'real_world_event_index.json'


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, set):
        return list(value)
    return [value]


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        x = float(value)
        if math.isnan(x) or math.isinf(x):
            return default
        return x
    except Exception:
        return default


def _bounded(value: Any, lo: float = 0.0, hi: float = 1.0) -> float:
    x = _safe_float(value, lo)
    return max(lo, min(hi, x))


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _dedupe_text(values: Any) -> list[str]:
    out: list[str] = []
    for item in _as_list(values):
        text = str(item).strip()
        if text and text not in out:
            out.append(text)
    return out


class RealWorldEventDetection:
    '''G9 real-world event detector.

    The detector compares observation(t) and observation(t+1), detects changes
    across visual, acoustic, sensor, runtime and environmental channels, then
    classifies, scores and persists events. It validates functional event
    detection only and never asserts phenomenal subjectivity.
    '''

    PRIMITIVE = PRIMITIVE
    PRIMITIVE_NAME = PRIMITIVE_NAME
    refinement = 'G9-R1'

    def __init__(self, root: Path | None = None) -> None:
        self.root = Path(root) if root is not None else ROOT
        self.event_dir = self.root / 'real_world_events'
        self.history_path = self.event_dir / 'real_world_event_detection_history.jsonl'
        self.latest_path = self.event_dir / 'latest_real_world_event_detection.json'
        self.event_index_path = self.event_dir / 'real_world_event_index.json'
        self._cycles = 0
        self._detected_events_total = 0

    def _default_previous(self) -> dict[str, Any]:
        return {
            'vision': {'detected_objects': ['baseline_object'], 'motion_detected': False},
            'audio': {'events': ['ambient'], 'amplitude': 0.1},
            'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.5},
            'runtime': {'storage_online': True, 'network_online': True},
        }

    def _default_current(self) -> dict[str, Any]:
        return {
            'vision': {'detected_objects': ['baseline_object'], 'motion_detected': False},
            'audio': {'events': ['ambient'], 'amplitude': 0.1},
            'sensors': {'temperature': 21.0, 'humidity': 0.45, 'light': 0.5},
            'runtime': {'storage_online': True, 'network_online': True},
        }

    def _load_previous_from_latest(self) -> dict[str, Any]:
        try:
            if self.latest_path.exists():
                data = json.loads(self.latest_path.read_text(encoding='utf-8'))
                latest_current = _as_dict(data.get('current_observation'))
                if latest_current:
                    return latest_current
        except Exception:
            pass
        return {}

    def _normalize_inputs(self, inputs: dict[str, Any] | None) -> dict[str, Any]:
        payload = _as_dict(inputs)
        previous = (
            _as_dict(payload.get('previous_observation'))
            or _as_dict(payload.get('observation_t'))
            or _as_dict(payload.get('before'))
            or _as_dict(payload.get('observation'))
        )
        current = (
            _as_dict(payload.get('current_observation'))
            or _as_dict(payload.get('observation_t1'))
            or _as_dict(payload.get('after'))
            or _as_dict(payload.get('post_observation'))
            or _as_dict(payload.get('measurement'))
        )
        if not previous and current:
            previous = self._load_previous_from_latest() or self._default_previous()
        if not previous:
            previous = self._default_previous()
        if not current:
            current = self._default_current()
        return {'previous_observation': previous, 'current_observation': current, 'raw_inputs': payload}

    def _environmental_state(self, observation: dict[str, Any], phase: str) -> dict[str, Any]:
        try:
            from ontology.environmental_state_model import EnvironmentalStateModel
            state = EnvironmentalStateModel(root=self.root).step(observation, persist=False)
            if isinstance(state, dict):
                state['event_detection_phase'] = phase
                return state
        except Exception as exc:
            return {
                'success': False,
                'primitive': 'environmental_state_model',
                'event_detection_phase': phase,
                'error': f'{type(exc).__name__}: {exc}',
                'state': {},
                'environment_class': 'unknown_environment',
                'environmental_state_stability': 0.0,
                'environmental_state_coherence': 0.0,
            }
        return {
            'success': False,
            'primitive': 'environmental_state_model',
            'event_detection_phase': phase,
            'state': {},
            'environment_class': 'unknown_environment',
            'environmental_state_stability': 0.0,
            'environmental_state_coherence': 0.0,
        }

    def _extract_channel(self, observation: dict[str, Any], env_state: dict[str, Any]) -> dict[str, Any]:
        nested = _as_dict(env_state.get('state'))
        vision_raw = _as_dict(observation.get('vision')) or _as_dict(nested.get('vision'))
        audio_raw = _as_dict(observation.get('audio')) or _as_dict(nested.get('audio'))
        sensor_raw = _as_dict(observation.get('sensors')) or _as_dict(observation.get('sensor')) or _as_dict(nested.get('sensors'))
        runtime_raw = _as_dict(observation.get('runtime')) or _as_dict(observation.get('system')) or _as_dict(nested.get('runtime'))

        detected_objects = (
            vision_raw.get('detected_objects')
            or vision_raw.get('objects')
            or vision_raw.get('object_labels')
            or []
        )
        audio_events = audio_raw.get('events') or audio_raw.get('detected_events') or audio_raw.get('event_labels') or []
        numeric_values = _as_dict(sensor_raw.get('numeric_values')) or {}
        for key, value in sensor_raw.items():
            if isinstance(value, (int, float)) and key not in numeric_values:
                numeric_values[key] = value

        runtime_flags: dict[str, Any] = {}
        for key, value in runtime_raw.items():
            if isinstance(value, (bool, str, int, float)):
                runtime_flags[key] = value

        return {
            'objects': set(_dedupe_text(detected_objects)),
            'audio_events': set(_dedupe_text(audio_events)),
            'motion_detected': bool(vision_raw.get('motion_detected', False)),
            'audio_amplitude': _safe_float(audio_raw.get('amplitude', audio_raw.get('volume', 0.0)), 0.0),
            'sensors': {str(k): _safe_float(v, 0.0) for k, v in numeric_values.items()},
            'runtime': runtime_flags,
            'environment_class': str(env_state.get('environment_class', 'unknown_environment')),
            'stability': _bounded(env_state.get('environmental_state_stability', 0.0)),
            'coherence': _bounded(env_state.get('environmental_state_coherence', 0.0)),
        }

    def _make_event(self, event_type: str, channel: str, description: str, severity: float, details: dict[str, Any]) -> dict[str, Any]:
        severity = _bounded(severity)
        if severity >= 0.75:
            severity_class = 'high'
        elif severity >= 0.35:
            severity_class = 'medium'
        elif severity > 0.0:
            severity_class = 'low'
        else:
            severity_class = 'none'
        return {
            'event_type': event_type,
            'channel': channel,
            'description': description,
            'severity': round(severity, 6),
            'severity_class': severity_class,
            'details': details,
        }

    def _detect_events(self, previous: dict[str, Any], current: dict[str, Any]) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []

        appeared = sorted(current['objects'] - previous['objects'])
        disappeared = sorted(previous['objects'] - current['objects'])
        if appeared:
            events.append(self._make_event('visual_object_appeared', 'vision', 'Objects appeared in the visual field.', min(1.0, 0.25 * len(appeared)), {'objects': appeared}))
        if disappeared:
            events.append(self._make_event('visual_object_disappeared', 'vision', 'Objects disappeared from the visual field.', min(1.0, 0.25 * len(disappeared)), {'objects': disappeared}))
        if previous['motion_detected'] != current['motion_detected']:
            events.append(self._make_event('visual_motion_state_changed', 'vision', 'Visual motion flag changed.', 0.45, {'previous': previous['motion_detected'], 'current': current['motion_detected']}))

        audio_started = sorted(current['audio_events'] - previous['audio_events'])
        audio_ended = sorted(previous['audio_events'] - current['audio_events'])
        if audio_started:
            events.append(self._make_event('acoustic_event_started', 'audio', 'New acoustic events started.', min(1.0, 0.30 * len(audio_started)), {'events': audio_started}))
        if audio_ended:
            events.append(self._make_event('acoustic_event_ended', 'audio', 'Acoustic events ended.', min(1.0, 0.25 * len(audio_ended)), {'events': audio_ended}))
        amp_delta = abs(current['audio_amplitude'] - previous['audio_amplitude'])
        if amp_delta >= 0.15:
            events.append(self._make_event('acoustic_amplitude_shift', 'audio', 'Audio amplitude changed beyond threshold.', min(1.0, amp_delta), {'previous': previous['audio_amplitude'], 'current': current['audio_amplitude'], 'delta': amp_delta}))

        sensor_keys = sorted(set(previous['sensors']) | set(current['sensors']))
        for key in sensor_keys:
            old = previous['sensors'].get(key)
            new = current['sensors'].get(key)
            if old is None or new is None:
                events.append(self._make_event('sensor_channel_presence_changed', 'sensor', 'Sensor channel appeared or disappeared.', 0.40, {'sensor': key, 'previous': old, 'current': new}))
                continue
            delta = abs(new - old)
            threshold = 0.10 if key in {'humidity', 'light'} else 0.5
            normalized = delta if key in {'humidity', 'light'} else delta / 10.0
            if delta >= threshold:
                events.append(self._make_event('sensor_value_shift', 'sensor', 'Sensor value changed beyond threshold.', min(1.0, normalized), {'sensor': key, 'previous': old, 'current': new, 'delta': delta}))

        runtime_keys = sorted(set(previous['runtime']) | set(current['runtime']))
        for key in runtime_keys:
            old = previous['runtime'].get(key)
            new = current['runtime'].get(key)
            if old != new:
                event_type = 'runtime_state_changed'
                if 'storage' in key or 'ssd' in key or 'volume' in key:
                    event_type = 'storage_state_changed'
                elif 'network' in key:
                    event_type = 'network_state_changed'
                events.append(self._make_event(event_type, 'runtime', 'Runtime or device state changed.', 0.65, {'field': key, 'previous': old, 'current': new}))

        if previous['environment_class'] != current['environment_class']:
            events.append(self._make_event('environment_class_changed', 'environment', 'Environmental class changed.', 0.55, {'previous': previous['environment_class'], 'current': current['environment_class']}))

        stability_delta = abs(current['stability'] - previous['stability'])
        coherence_delta = abs(current['coherence'] - previous['coherence'])
        if stability_delta >= 0.20:
            events.append(self._make_event('environmental_stability_shift', 'environment', 'Environmental stability changed beyond threshold.', stability_delta, {'previous': previous['stability'], 'current': current['stability'], 'delta': stability_delta}))
        if coherence_delta >= 0.20:
            events.append(self._make_event('environmental_coherence_shift', 'environment', 'Environmental coherence changed beyond threshold.', coherence_delta, {'previous': previous['coherence'], 'current': current['coherence'], 'delta': coherence_delta}))

        return events

    def _anomaly_context(self, events: list[dict[str, Any]]) -> dict[str, Any]:
        severities = [float(e.get('severity', 0.0)) for e in events]
        high_events = [e for e in events if e.get('severity_class') == 'high']
        return {
            'event_count': len(events),
            'mean_severity': round(_mean(severities), 6),
            'max_severity': round(max(severities) if severities else 0.0, 6),
            'high_severity_events': len(high_events),
            'anomaly_candidate': bool(high_events),
        }

    def _maybe_record_civilizational_memory(self, result: dict[str, Any]) -> dict[str, Any]:
        if result.get('detected_events', 0) <= 0:
            return {'attempted': False, 'success': False, 'reason': 'no_event'}
        try:
            from ontology.civilizational_memory_archive import CivilizationalMemoryArchive
            archive = CivilizationalMemoryArchive(root=self.root)
            record = archive.step(
                category='real_world_event',
                content={
                    'primitive': PRIMITIVE,
                    'timestamp_utc': result.get('timestamp_utc'),
                    'detected_events': result.get('detected_events'),
                    'event_severity_index': result.get('event_severity_index'),
                    'events': result.get('events', []),
                },
            )
            return {'attempted': True, 'success': bool(_as_dict(record).get('archive_success', False)), 'record': record}
        except Exception as exc:
            return {'attempted': True, 'success': False, 'error': f'{type(exc).__name__}: {exc}'}

    def _persist(self, result: dict[str, Any]) -> None:
        self.event_dir.mkdir(parents=True, exist_ok=True)
        self.history_path.parent.mkdir(parents=True, exist_ok=True)
        with self.history_path.open('a', encoding='utf-8') as f:
            f.write(json.dumps(result, ensure_ascii=False, sort_keys=True) + '\n')
        self.latest_path.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')
        index = {
            'primitive': PRIMITIVE,
            'updated_at_utc': result.get('timestamp_utc'),
            'last_detected_events': result.get('detected_events', 0),
            'last_event_severity_index': result.get('event_severity_index', 0.0),
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
        }
        self.event_index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')

    def step(self, inputs: dict[str, Any] | None = None, persist: bool = False) -> dict[str, Any]:
        self._cycles += 1
        normalized = self._normalize_inputs(inputs)
        previous_observation = normalized['previous_observation']
        current_observation = normalized['current_observation']

        previous_env = self._environmental_state(previous_observation, 'previous')
        current_env = self._environmental_state(current_observation, 'current')
        previous_channel = self._extract_channel(previous_observation, previous_env)
        current_channel = self._extract_channel(current_observation, current_env)
        events = self._detect_events(previous_channel, current_channel)

        detected_events = len(events)
        self._detected_events_total += detected_events
        severities = [float(e.get('severity', 0.0)) for e in events]
        event_severity_index = round(max(severities) if severities else 0.0, 6)
        environmental_change_rate = round(_mean(severities), 6)
        event_detection_rate = round(detected_events / max(1, detected_events + 1), 6) if detected_events else 0.0
        channels = sorted({str(e.get('channel')) for e in events})
        anomaly_context = self._anomaly_context(events)

        result: dict[str, Any] = {
            'success': True,
            'primitive': PRIMITIVE,
            'refinement': 'G9-R1',
            'timestamp_utc': _now(),
            'event_detection_cycles': self._cycles,
            'detected_events': detected_events,
            'event_detection_rate': event_detection_rate,
            'event_severity_index': event_severity_index,
            'environmental_change_rate': environmental_change_rate,
            'events': events,
            'event_channels': channels,
            'anomaly_context': anomaly_context,
            'previous_observation': previous_observation,
            'current_observation': current_observation,
            'previous_environment_class': previous_channel['environment_class'],
            'current_environment_class': current_channel['environment_class'],
            'history_path': str(self.history_path),
            'latest_path': str(self.latest_path),
            'metrics': {
                'detected_events': detected_events,
                'event_detection_rate': event_detection_rate,
                'event_severity_index': event_severity_index,
                'environmental_change_rate': environmental_change_rate,
                'cumulative_detected_events': self._detected_events_total,
            },
            'diagnostics': {
                'functional_validation_only': True,
                'phenomenal_subjectivity_claimed': False,
                'non_redundant_role': 'observation_delta_event_classification_severity_historization',
                'real_physical_action_performed': False,
                'governance_preserved': True,
                'non_closure_preserved': True,
                'dangerous_action_surface_added': False,
                'dependencies': DEPENDENCIES,
            },
        }

        if persist:
            self._persist(result)
            result['persisted'] = True
            result['memory_archive'] = self._maybe_record_civilizational_memory(result)
        else:
            result['persisted'] = False

        return result


# Backward-compatible alias for simple discovery patterns.
RealWorldEventDetector = RealWorldEventDetection
